In [995]:
import ast
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

In [996]:
from pathlib import Path

folder = Path(r"C:\Users\Shiva Thakur\OneDrive\Desktop\Github\Projects\Python\E_Big4_India")

data_dict = {f.stem: pd.read_csv(f) for f in folder.glob("*.csv")}

In [997]:
clients = data_dict['Clients']

print("Shape:", clients.shape)
clients.head()

Shape: (120000, 5)

   Client_ID  Company    Industry Country  ContractValue
0          1    Wipro      Retail   India       39728043
1          2      TCS  Healthcare   India       41065784
2          3    Wipro  Healthcare   India       32180187
3          4      TCS  Healthcare  Canada        7905343
4          5  Infosys      Retail      UK       15392192

##### Names of all tables

In [998]:
print(list(data_dict.keys()))

['Clients', 'Company_Financials', 'Employees', 'Office_Locations', 'Projects', 'Technologies']

##### # **Type A — Load & explore**

##### 1. Load `clients.csv` and display the first 5 rows and the shape.

In [999]:
data_dict['Clients'].head()

   Client_ID  Company    Industry Country  ContractValue
0          1    Wipro      Retail   India       39728043
1          2      TCS  Healthcare   India       41065784
2          3    Wipro  Healthcare   India       32180187
3          4      TCS  Healthcare  Canada        7905343
4          5  Infosys      Retail      UK       15392192

##### 2. Load `employees.csv` and check data types with `.info()`.

In [1000]:
data_dict['Employees'].info()

<class 'pandas.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 7 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Employee_ID  250000 non-null  int64
 1   Company      250000 non-null  str
 2   Department   250000 non-null  str
 3   Role         250000 non-null  str
 4   Age          250000 non-null  int64
 5   Salary       250000 non-null  int64
 6   JoinDate     250000 non-null  str
dtypes: int64(3), str(4)
memory usage: 13.4 MB

In [1001]:
print(list(data_dict.keys()))

['Clients', 'Company_Financials', 'Employees', 'Office_Locations', 'Projects', 'Technologies']

##### 3. Load `projects.csv` and check for missing values per column.

In [1002]:
data_dict['Projects'].isnull().sum()

Project_ID     0
Company        0
Client_ID      0
Employee_ID    0
Technology     0
Budget         0
Status         0
dtype: int64

In [1003]:
print(list(data_dict.keys()))

['Clients', 'Company_Financials', 'Employees', 'Office_Locations', 'Projects', 'Technologies']

##### 4. Load `offices.csv` and list all column names.

In [1004]:
data_dict['Office_Locations'].columns

print('Column names for the table Office_Locations are :', data_dict['Office_Locations'].columns)

Column names for the table Office_Locations are : Index(['Office_ID', 'Company', 'Country', 'State', 'City', 'Employees'], dtype='str')

##### 5. Load `technologies.csv` and check for duplicate rows with `.duplicated()`.

In [1005]:
data_dict['Technologies'].duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
149995    False
149996    False
149997    False
149998    False
149999    False
Length: 150000, dtype: bool

##### **Type B — Column selection**

##### 6. From `clients`, select just `Company` and `Industry`.

In [1006]:
data_dict['Clients'][['Company','Industry']]

        Company    Industry
0         Wipro      Retail
1           TCS  Healthcare
2         Wipro  Healthcare
3           TCS  Healthcare
4       Infosys      Retail
...         ...         ...
119995  HCLTech  Healthcare
119996      TCS     Telecom
119997    Wipro     Banking
119998  Infosys  Healthcare
119999  Infosys     Telecom

[120000 rows x 2 columns]

In [1007]:
print(list(data_dict.keys()))

['Clients', 'Company_Financials', 'Employees', 'Office_Locations', 'Projects', 'Technologies']

##### 7. From `employees`, select `Employee_ID`, `Role`, and `Salary`.

In [1008]:
data_dict['Employees'][['Employee_ID','Role','Salary']]

        Employee_ID    Role  Salary
0                 1      QA   91806
1                 2      SE   14827
2                 3      BA  121727
3                 4     SSE   88985
4                 5      SE   35904
...             ...     ...     ...
249995       249996  DevOps   29369
249996       249997      QA   65865
249997       249998      QA   48007
249998       249999      SE   65756
249999       250000      QA  113592

[250000 rows x 3 columns]

In [1009]:
print(list(data_dict.keys()))

['Clients', 'Company_Financials', 'Employees', 'Office_Locations', 'Projects', 'Technologies']

##### 8. From `projects`, select `Project_ID`, `Technology`, and `Status`.

In [1010]:
data_dict['Projects'][['Project_ID','Technology','Status']]

        Project_ID Technology       Status
0                1      Azure  In Progress
1                2      Azure      On Hold
2                3        AWS      On Hold
3                4       Java      On Hold
4                5        GCP  In Progress
...            ...        ...          ...
179995      179996       Java    Completed
179996      179997        GCP    Completed
179997      179998        AWS    Completed
179998      179999        GCP  In Progress
179999      180000     Python  In Progress

[180000 rows x 3 columns]

##### 10. From `financials`, select `Company`, `Year`, and `Revenue`.

In [1011]:
data_dict['Company_Financials'][['Company', 'Year', 'Revenue']]

        Company  Year  Revenue
0           TCS  2015     4812
1           TCS  2025     7712
2           TCS  2018     1234
3       HCLTech  2018     5357
4       Infosys  2026     6374
...         ...   ...      ...
119995  Infosys  2017     8410
119996      TCS  2015     5936
119997  Infosys  2016     3715
119998  HCLTech  2025     1416
119999  HCLTech  2022     3698

[120000 rows x 3 columns]

##### **Type C — Filtering rows**

##### 11. Filter `clients` to only rows where `Industry == 'Retail'`.

In [1012]:
print(list(data_dict.keys()))

['Clients', 'Company_Financials', 'Employees', 'Office_Locations', 'Projects', 'Technologies']

In [1013]:
data_dict['Clients'].loc[data_dict['Clients']['Industry'] == 'Retail'].head()

    Client_ID  Company Industry Country  ContractValue
0           1    Wipro   Retail   India       39728043
4           5  Infosys   Retail      UK       15392192
6           7    Wipro   Retail      UK       39845758
13         14  Infosys   Retail  Canada       26940688
16         17    Wipro   Retail      UK       13172681

##### 12. Filter `employees` to only rows where `Department == 'AI'`.

In [1014]:
print(list(data_dict.keys()))

['Clients', 'Company_Financials', 'Employees', 'Office_Locations', 'Projects', 'Technologies']

In [1015]:
data_dict['Employees'].loc[data_dict['Employees']['Department'] == 'AI'].head()

    Employee_ID  Company Department    Role  Age  Salary    JoinDate
0             1    Wipro         AI      QA   50   91806  11-04-2020
9            10  Infosys         AI      QA   49   27540  20-04-2020
18           19  Infosys         AI  DevOps   57  104793  29-04-2020
22           23  HCLTech         AI     SSE   33   57850  03-05-2020
24           25      TCS         AI      PM   35   92132  05-05-2020

##### 13. Filter `projects` to only rows where `Status == 'In Progress'`.

In [1016]:
print(list(data_dict.keys()))

['Clients', 'Company_Financials', 'Employees', 'Office_Locations', 'Projects', 'Technologies']

In [1017]:
data_dict['Projects'].loc[data_dict['Projects']['Status'] == 'In Progress'].head()

,Project_ID,Company,Client_ID,Employee_ID,Technology,Budget,Status
0,1,Wipro,32252,195820,Azure,8646817,In Progress
4,5,TCS,114709,100718,GCP,4313680,In Progress
6,7,HCLTech,113542,186129,Java,5171519,In Progress
7,8,TCS,72965,39418,Java,6434833,In Progress
9,10,HCLTech,59848,86628,SAP,133948,In Progress

##### 14. Filter `offices` to only rows where `Country == 'India'`.

In [1018]:
print(list(data_dict.keys()))

['Clients', 'Company_Financials', 'Employees', 'Office_Locations', 'Projects', 'Technologies']

In [1019]:
data_dict['Office_Locations'].head()

   Office_ID  Company Country State       City  Employees
0          1    Wipro  Canada    KA       Pune      10757
1          2  HCLTech   India    TS       Pune       7143
2          3    Wipro      UK    TS    Chennai       8807
3          4  HCLTech  Canada    WB    Chennai       3058
4          5    Wipro  Canada    TN  Bengaluru       8998

In [1020]:
data_dict['Office_Locations'].loc[data_dict['Office_Locations']['Country'] == 'India'].head()

    Office_ID  Company Country State     City  Employees
1           2  HCLTech   India    TS     Pune       7143
5           6      TCS   India    TN  Kolkata       8237
7           8    Wipro   India    WB     Pune      13110
11         12  Infosys   India    TS     Pune       5469
16         17    Wipro   India    KA  Kolkata      12903

##### 15. Filter `financials` to only rows where `Year == 2021`.

In [1021]:
print(list(data_dict.keys()))

['Clients', 'Company_Financials', 'Employees', 'Office_Locations', 'Projects', 'Technologies']

In [1022]:
data_dict['Company_Financials'].head()

   Financial_ID  Company  Year Quarter  Revenue  Profit  Employees
0             1      TCS  2015      Q3     4812     994      86579
1             2      TCS  2025      Q1     7712     210      57811
2             3      TCS  2018      Q2     1234    2378     102124
3             4  HCLTech  2018      Q4     5357     106     248916
4             5  Infosys  2026      Q4     6374    1218      90758

In [1023]:
data_dict['Company_Financials'].loc[data_dict['Company_Financials']['Year'] == 2021 ].head()

    Financial_ID  Company  Year Quarter  Revenue  Profit  Employees
7              8      TCS  2021      Q1     5603    1561     201349
14            15    Wipro  2021      Q3     1884     944     198682
42            43      TCS  2021      Q3     8254    1248     160888
60            61  Infosys  2021      Q2     1485    1342     145591
70            71    Wipro  2021      Q1     7111    2441      99828

##### **Type D — `.value_counts()`**

##### 16. Count how many clients fall into each `Industry`.

In [1024]:
print(list(data_dict.keys()))

['Clients', 'Company_Financials', 'Employees', 'Office_Locations', 'Projects', 'Technologies']

In [1025]:
data_dict['Clients'].head()

   Client_ID  Company    Industry Country  ContractValue
0          1    Wipro      Retail   India       39728043
1          2      TCS  Healthcare   India       41065784
2          3    Wipro  Healthcare   India       32180187
3          4      TCS  Healthcare  Canada        7905343
4          5  Infosys      Retail      UK       15392192

In [1026]:
data_dict['Clients']['Industry'].value_counts()

Industry
Healthcare       24115
Manufacturing    24041
Retail           24018
Banking          23965
Telecom          23861
Name: count, dtype: int64

##### 17. Count how many employees fall into each `Department`.

In [1027]:
print(list(data_dict.keys()))

['Clients', 'Company_Financials', 'Employees', 'Office_Locations', 'Projects', 'Technologies']

In [1028]:
data_dict['Employees'].head()

   Employee_ID  Company   Department Role  Age  Salary    JoinDate
0            1    Wipro           AI   QA   50   91806  11-04-2020
1            2    Wipro      Finance   SE   21   14827  12-04-2020
2            3    Wipro      Finance   BA   49  121727  13-04-2020
3            4    Wipro  Engineering  SSE   43   88985  14-04-2020
4            5  Infosys      Finance   SE   25   35904  15-04-2020

In [1029]:
data_dict['Employees']['Department'].value_counts()

Department
Support        31545
Finance        31396
AI             31325
Engineering    31222
HR             31214
Sales          31211
Cloud          31157
IT             30930
Name: count, dtype: int64

##### 18. Count how many projects fall into each `Status`.

In [1030]:
data_dict['Projects'].head()

,Project_ID,Company,Client_ID,Employee_ID,Technology,Budget,Status
0,1,Wipro,32252,195820,Azure,8646817,In Progress
1,2,Wipro,21042,69871,Azure,6633547,On Hold
2,3,HCLTech,89295,148126,AWS,5647221,On Hold
3,4,Infosys,54119,115503,Java,7970162,On Hold
4,5,TCS,114709,100718,GCP,4313680,In Progress

In [1031]:
data_dict['Projects']['Status'].value_counts()

Status
Completed      60121
On Hold        60032
In Progress    59847
Name: count, dtype: int64

##### 19. Count how many offices exist per `Company`.

In [1032]:
data_dict['Office_Locations'].head()

   Office_ID  Company Country State       City  Employees
0          1    Wipro  Canada    KA       Pune      10757
1          2  HCLTech   India    TS       Pune       7143
2          3    Wipro      UK    TS    Chennai       8807
3          4  HCLTech  Canada    WB    Chennai       3058
4          5    Wipro  Canada    TN  Bengaluru       8998

In [1033]:
data_dict['Office_Locations']['Company'].value_counts()

Company
Infosys    25163
TCS        25010
HCLTech    24963
Wipro      24864
Name: count, dtype: int64

##### 20. Count how many technologies fall into each `Technology` name.

In [1034]:
data_dict['Technologies'].head()

   Technology_ID  Company Technology  Project_ID  Popularity
0              1  HCLTech        SAP      153468       57.75
1              2    Wipro        SAP       48952       57.73
2              3  HCLTech      Azure      146403       78.35
3              4      TCS     Python       39073       75.26
4              5      TCS      Azure       50553       85.76

In [1035]:
data_dict['Technologies']['Technology'].value_counts()

Technology
AWS       25132
Java      25092
Python    25029
Azure     24962
SAP       24923
GCP       24862
Name: count, dtype: int64

##### **Type A — Single aggregate**

##### 1. Calculate the average `Salary` in `employees`.

In [1036]:
data_dict['Employees'].head()

   Employee_ID  Company   Department Role  Age  Salary    JoinDate
0            1    Wipro           AI   QA   50   91806  11-04-2020
1            2    Wipro      Finance   SE   21   14827  12-04-2020
2            3    Wipro      Finance   BA   49  121727  13-04-2020
3            4    Wipro  Engineering  SSE   43   88985  14-04-2020
4            5  Infosys      Finance   SE   25   35904  15-04-2020

In [1037]:
data_dict['Employees']['Salary'].mean()

print(f'Average salary of employees is: {data_dict['Employees']['Salary'].mean():.2f}')

Average salary of employees is: 78895.84

##### 2. Calculate the total `ContractValue` in `clients`.

In [1038]:
data_dict['Clients'].head()

   Client_ID  Company    Industry Country  ContractValue
0          1    Wipro      Retail   India       39728043
1          2      TCS  Healthcare   India       41065784
2          3    Wipro  Healthcare   India       32180187
3          4      TCS  Healthcare  Canada        7905343
4          5  Infosys      Retail      UK       15392192

In [1039]:
data_dict['Clients']['ContractValue'].sum()

print(f'The total contract value in clients is :{data_dict['Clients']['ContractValue'].sum():.2f}')

The total contract value in clients is :2999443706423.00

##### 3. Find the maximum `Budget` in `projects`.

In [1040]:
data_dict['Projects'].head()

,Project_ID,Company,Client_ID,Employee_ID,Technology,Budget,Status
0,1,Wipro,32252,195820,Azure,8646817,In Progress
1,2,Wipro,21042,69871,Azure,6633547,On Hold
2,3,HCLTech,89295,148126,AWS,5647221,On Hold
3,4,Infosys,54119,115503,Java,7970162,On Hold
4,5,TCS,114709,100718,GCP,4313680,In Progress

In [1041]:
data_dict['Projects']['Budget'].max()

print(f'Maximum Budget in projects is: {data_dict['Projects']['Budget'].max():.2f}')

Maximum Budget in projects is: 9999902.00

##### 4. Find the minimum `Profit` in `financials`.

In [1042]:
data_dict['Company_Financials'].head()

   Financial_ID  Company  Year Quarter  Revenue  Profit  Employees
0             1      TCS  2015      Q3     4812     994      86579
1             2      TCS  2025      Q1     7712     210      57811
2             3      TCS  2018      Q2     1234    2378     102124
3             4  HCLTech  2018      Q4     5357     106     248916
4             5  Infosys  2026      Q4     6374    1218      90758

In [1043]:
data_dict['Company_Financials']['Profit'].min()

print(f'The minimum profit in finance is : {data_dict['Company_Financials']['Profit'].min():.2f}')

The minimum profit in finance is : 80.00

##### 5. Count the total number of rows in `offices`.

In [1044]:
data_dict['Office_Locations'].head()

   Office_ID  Company Country State       City  Employees
0          1    Wipro  Canada    KA       Pune      10757
1          2  HCLTech   India    TS       Pune       7143
2          3    Wipro      UK    TS    Chennai       8807
3          4  HCLTech  Canada    WB    Chennai       3058
4          5    Wipro  Canada    TN  Bengaluru       8998

In [1045]:
len(data_dict['Office_Locations'])

print(f'Total number of rows in office table are : {len(data_dict['Office_Locations'])}')

Total number of rows in office table are : 100000

##### **Type B — `.groupby()` + `.count()` / `.size()`**

##### 6. Group `employees` by `Department` and count employees in each.

In [1046]:
data_dict['Employees'].head()

   Employee_ID  Company   Department Role  Age  Salary    JoinDate
0            1    Wipro           AI   QA   50   91806  11-04-2020
1            2    Wipro      Finance   SE   21   14827  12-04-2020
2            3    Wipro      Finance   BA   49  121727  13-04-2020
3            4    Wipro  Engineering  SSE   43   88985  14-04-2020
4            5  Infosys      Finance   SE   25   35904  15-04-2020

In [1047]:
data_dict['Employees'].groupby('Department').size()

Department
AI             31325
Cloud          31157
Engineering    31222
Finance        31396
HR             31214
IT             30930
Sales          31211
Support        31545
dtype: int64

##### 7. Group `clients` by `Industry` and count clients in each.

In [1048]:
data_dict['Clients'].head()

   Client_ID  Company    Industry Country  ContractValue
0          1    Wipro      Retail   India       39728043
1          2      TCS  Healthcare   India       41065784
2          3    Wipro  Healthcare   India       32180187
3          4      TCS  Healthcare  Canada        7905343
4          5  Infosys      Retail      UK       15392192

In [1049]:
data_dict['Clients'].groupby('Industry').size()

Industry
Banking          23965
Healthcare       24115
Manufacturing    24041
Retail           24018
Telecom          23861
dtype: int64

##### 8. Group `projects` by `Status` and count projects in each.

In [1050]:
data_dict['Projects'].head()

,Project_ID,Company,Client_ID,Employee_ID,Technology,Budget,Status
0,1,Wipro,32252,195820,Azure,8646817,In Progress
1,2,Wipro,21042,69871,Azure,6633547,On Hold
2,3,HCLTech,89295,148126,AWS,5647221,On Hold
3,4,Infosys,54119,115503,Java,7970162,On Hold
4,5,TCS,114709,100718,GCP,4313680,In Progress

In [1051]:
data_dict['Projects'].groupby('Status').size()

Status
Completed      60121
In Progress    59847
On Hold        60032
dtype: int64

##### 9. Group `offices` by `Country` and count offices in each.

In [1052]:
data_dict['Office_Locations'].head()

   Office_ID  Company Country State       City  Employees
0          1    Wipro  Canada    KA       Pune      10757
1          2  HCLTech   India    TS       Pune       7143
2          3    Wipro      UK    TS    Chennai       8807
3          4  HCLTech  Canada    WB    Chennai       3058
4          5    Wipro  Canada    TN  Bengaluru       8998

In [1053]:
data_dict['Office_Locations'].groupby('Country').size()

Country
Canada     19919
Germany    19994
India      20019
UK         20068
USA        20000
dtype: int64

##### 10. Group `financials` by `Company` and count records in each.

In [1054]:
data_dict['Company_Financials'].head()

   Financial_ID  Company  Year Quarter  Revenue  Profit  Employees
0             1      TCS  2015      Q3     4812     994      86579
1             2      TCS  2025      Q1     7712     210      57811
2             3      TCS  2018      Q2     1234    2378     102124
3             4  HCLTech  2018      Q4     5357     106     248916
4             5  Infosys  2026      Q4     6374    1218      90758

In [1055]:
data_dict['Company_Financials'].groupby('Company').size()

Company
HCLTech    29753
Infosys    29963
TCS        30186
Wipro      30098
dtype: int64

##### **Type C — `.groupby()` + `.mean()` / `.sum()`**

##### 11. Group `employees` by `Department` and find average `Salary`.

In [1056]:
data_dict['Employees'].head()

   Employee_ID  Company   Department Role  Age  Salary    JoinDate
0            1    Wipro           AI   QA   50   91806  11-04-2020
1            2    Wipro      Finance   SE   21   14827  12-04-2020
2            3    Wipro      Finance   BA   49  121727  13-04-2020
3            4    Wipro  Engineering  SSE   43   88985  14-04-2020
4            5  Infosys      Finance   SE   25   35904  15-04-2020

In [1057]:
data_dict['Employees'].groupby('Department')['Salary'].mean().round(2)

Department
AI             79439.99
Cloud          78825.29
Engineering    78711.19
Finance        78867.22
HR             78975.95
IT             78833.82
Sales          78837.07
Support        78676.08
Name: Salary, dtype: float64

##### 12. Group `clients` by `Industry` and find total `ContractValue`.

In [1058]:
data_dict['Clients'].head()

   Client_ID  Company    Industry Country  ContractValue
0          1    Wipro      Retail   India       39728043
1          2      TCS  Healthcare   India       41065784
2          3    Wipro  Healthcare   India       32180187
3          4      TCS  Healthcare  Canada        7905343
4          5  Infosys      Retail      UK       15392192

In [1059]:
data_dict['Clients'].groupby('Industry')['ContractValue'].mean()

Industry
Banking          2.499614e+07
Healthcare       2.489478e+07
Manufacturing    2.509016e+07
Retail           2.495520e+07
Telecom          2.504116e+07
Name: ContractValue, dtype: float64

##### 13. Group `projects` by `Technology` and find average `Budget`.

In [1060]:
print(list(data_dict.keys()))

['Clients', 'Company_Financials', 'Employees', 'Office_Locations', 'Projects', 'Technologies']

In [1061]:
data_dict['Projects'].head()

,Project_ID,Company,Client_ID,Employee_ID,Technology,Budget,Status
0,1,Wipro,32252,195820,Azure,8646817,In Progress
1,2,Wipro,21042,69871,Azure,6633547,On Hold
2,3,HCLTech,89295,148126,AWS,5647221,On Hold
3,4,Infosys,54119,115503,Java,7970162,On Hold
4,5,TCS,114709,100718,GCP,4313680,In Progress

In [1062]:
data_dict['Projects'].groupby('Technology').size()

Technology
AWS       29989
Azure     30103
GCP       30033
Java      29899
Python    30038
SAP       29938
dtype: int64

In [1063]:
data_dict['Projects'].groupby('Technology')['Budget'].mean()

Technology
AWS       5.031285e+06
Azure     5.003498e+06
GCP       5.021909e+06
Java      5.028624e+06
Python    5.034717e+06
SAP       5.038316e+06
Name: Budget, dtype: float64

##### 14. Group `financials` by `Company` and find total `Revenue`.

In [1064]:
data_dict['Company_Financials'].head()

   Financial_ID  Company  Year Quarter  Revenue  Profit  Employees
0             1      TCS  2015      Q3     4812     994      86579
1             2      TCS  2025      Q1     7712     210      57811
2             3      TCS  2018      Q2     1234    2378     102124
3             4  HCLTech  2018      Q4     5357     106     248916
4             5  Infosys  2026      Q4     6374    1218      90758

In [1065]:
data_dict['Company_Financials'].groupby('Company').size()

Company
HCLTech    29753
Infosys    29963
TCS        30186
Wipro      30098
dtype: int64

In [1066]:
data_dict['Company_Financials'].groupby('Company')['Revenue'].mean()

Company
HCLTech    4905.237959
Infosys    4910.797650
TCS        4908.652885
Wipro      4880.339059
Name: Revenue, dtype: float64

##### 15. Group `technologies` by `Technology` and find average `Popularity`.

In [1067]:
data_dict['Technologies'].head()

   Technology_ID  Company Technology  Project_ID  Popularity
0              1  HCLTech        SAP      153468       57.75
1              2    Wipro        SAP       48952       57.73
2              3  HCLTech      Azure      146403       78.35
3              4      TCS     Python       39073       75.26
4              5      TCS      Azure       50553       85.76

In [1068]:
data_dict['Technologies'].groupby('Technology')['Popularity'].mean()

Technology
AWS       74.988675
Azure     74.957781
GCP       74.961102
Java      74.878793
Python    74.860119
SAP       74.989803
Name: Popularity, dtype: float64

##### **Type D — `.groupby()` + `.agg()` (multiple stats at once)**

##### 16. Group `employees` by `Department` and get both mean and max `Salary` in one `.agg()`.

In [1069]:
data_dict['Employees'].head()

   Employee_ID  Company   Department Role  Age  Salary    JoinDate
0            1    Wipro           AI   QA   50   91806  11-04-2020
1            2    Wipro      Finance   SE   21   14827  12-04-2020
2            3    Wipro      Finance   BA   49  121727  13-04-2020
3            4    Wipro  Engineering  SSE   43   88985  14-04-2020
4            5  Infosys      Finance   SE   25   35904  15-04-2020

In [1070]:
data_dict['Employees'].groupby('Department')['Salary'].agg(['mean', 'max']).round(2)

                 mean     max
Department
AI           79439.99  149997
Cloud        78825.29  149993
Engineering  78711.19  149994
Finance      78867.22  150000
HR           78975.95  149998
IT           78833.82  149994
Sales        78837.07  149996
Support      78676.08  150000

##### 17. Group `clients` by `Industry` and get both sum and count of `ContractValue`.

In [1071]:
data_dict['Clients'].groupby('Industry')['ContractValue'].agg(['sum','count']).round(2)

                        sum  count
Industry
Banking        599032568528  23965
Healthcare     600337613772  24115
Manufacturing  603192574026  24041
Retail         599373926642  24018
Telecom        597507023455  23861

##### 18. Group `projects` by `Status` and get min, max, and mean `Budget`.

In [1072]:
data_dict['Projects'].head()

,Project_ID,Company,Client_ID,Employee_ID,Technology,Budget,Status
0,1,Wipro,32252,195820,Azure,8646817,In Progress
1,2,Wipro,21042,69871,Azure,6633547,On Hold
2,3,HCLTech,89295,148126,AWS,5647221,On Hold
3,4,Infosys,54119,115503,Java,7970162,On Hold
4,5,TCS,114709,100718,GCP,4313680,In Progress

In [1073]:
data_dict['Projects'].groupby('Status')['Budget'].agg(['min','max','mean']).round(2)

               min      max        mean
Status
Completed    50028  9999892  5032316.90
In Progress  50117  9999902  5032367.76
On Hold      50603  9999770  5014446.16

##### 19. Group `financials` by `Company` and get sum of `Revenue` and sum of `Profit`.

In [1074]:
data_dict['Company_Financials'].head()

   Financial_ID  Company  Year Quarter  Revenue  Profit  Employees
0             1      TCS  2015      Q3     4812     994      86579
1             2      TCS  2025      Q1     7712     210      57811
2             3      TCS  2018      Q2     1234    2378     102124
3             4  HCLTech  2018      Q4     5357     106     248916
4             5  Infosys  2026      Q4     6374    1218      90758

In [1075]:
data_dict['Company_Financials'].groupby('Company').agg({'Revenue':'sum','Profit':'sum'}).round(2)

           Revenue    Profit
Company
HCLTech  145945545  38386932
Infosys  147142230  38631594
TCS      148172596  38854753
Wipro    146888445  38847877

##### 20. Group `offices` by `Company` and get count of offices and sum of `Employees`.

In [1076]:
data_dict['Office_Locations'].head()

   Office_ID  Company Country State       City  Employees
0          1    Wipro  Canada    KA       Pune      10757
1          2  HCLTech   India    TS       Pune       7143
2          3    Wipro      UK    TS    Chennai       8807
3          4  HCLTech  Canada    WB    Chennai       3058
4          5    Wipro  Canada    TN  Bengaluru       8998

In [1077]:
data_dict['Office_Locations'].groupby('Company')['Employees'].agg(['sum']).round(2)
#Single condition aggrigate

               sum
Company
HCLTech  187341532
Infosys  189072363
TCS      187591141
Wipro    186057600

In [1078]:
data_dict['Office_Locations'].groupby('Company').agg({'Office_ID':'count','Employees':'sum'}).round(2)
#Multi condition aggrigate

         Office_ID  Employees
Company
HCLTech      24963  187341532
Infosys      25163  189072363
TCS          25010  187591141
Wipro        24864  186057600

##### **Type A — `.sort_values()` basics**

##### 1. Sort `employees` by `Salary` descending.

In [1079]:
data_dict['Employees'].head()

   Employee_ID  Company   Department Role  Age  Salary    JoinDate
0            1    Wipro           AI   QA   50   91806  11-04-2020
1            2    Wipro      Finance   SE   21   14827  12-04-2020
2            3    Wipro      Finance   BA   49  121727  13-04-2020
3            4    Wipro  Engineering  SSE   43   88985  14-04-2020
4            5  Infosys      Finance   SE   25   35904  15-04-2020

In [1080]:
data_dict['Employees'].sort_values( by = 'Salary', ascending = False ).head()

        Employee_ID  Company Department Role  Age  Salary    JoinDate
241621       241622      TCS    Finance  SSE   45  150000  24-10-2681
81995         81996    Wipro    Finance   DS   35  150000  09-10-2244
129810       129811    Wipro    Support   QA   26  150000  08-09-2375
182728       182729      TCS         HR   QA   48  149998  27-07-2520
46759         46760  HCLTech    Support   DS   21  149998  19-04-2148

##### 2. Sort `clients` by `ContractValue` ascending.

In [1081]:
data_dict['Clients'].head()

   Client_ID  Company    Industry Country  ContractValue
0          1    Wipro      Retail   India       39728043
1          2      TCS  Healthcare   India       41065784
2          3    Wipro  Healthcare   India       32180187
3          4      TCS  Healthcare  Canada        7905343
4          5  Infosys      Retail      UK       15392192

In [1082]:
data_dict['Clients'].sort_values( by = 'ContractValue', ascending = True ).head()

        Client_ID  Company       Industry Country  ContractValue
70866       70867  HCLTech         Retail   India         100589
34495       34496    Wipro        Telecom   India         101160
65988       65989  Infosys        Banking  Canada         101164
100382     100383    Wipro        Telecom      UK         101593
23859       23860      TCS  Manufacturing      UK         101873

##### 3. Sort `projects` by `Budget` descending.

In [1083]:
data_dict['Projects'].head()

,Project_ID,Company,Client_ID,Employee_ID,Technology,Budget,Status
0,1,Wipro,32252,195820,Azure,8646817,In Progress
1,2,Wipro,21042,69871,Azure,6633547,On Hold
2,3,HCLTech,89295,148126,AWS,5647221,On Hold
3,4,Infosys,54119,115503,Java,7970162,On Hold
4,5,TCS,114709,100718,GCP,4313680,In Progress

In [1084]:
data_dict['Projects'].sort_values( by = 'Budget', ascending = False ).head()

,Project_ID,Company,Client_ID,Employee_ID,Technology,Budget,Status
53884,53885,HCLTech,72801,230397,Azure,9999902,In Progress
32513,32514,Wipro,25174,143144,SAP,9999892,Completed
117146,117147,Wipro,4039,49372,Azure,9999770,On Hold
22244,22245,HCLTech,65861,119656,Java,9999724,On Hold
80257,80258,HCLTech,99498,186314,Java,9999704,On Hold

##### 4. Sort `financials` by `Revenue` descending.

In [1085]:
data_dict['Company_Financials'].head()

   Financial_ID  Company  Year Quarter  Revenue  Profit  Employees
0             1      TCS  2015      Q3     4812     994      86579
1             2      TCS  2025      Q1     7712     210      57811
2             3      TCS  2018      Q2     1234    2378     102124
3             4  HCLTech  2018      Q4     5357     106     248916
4             5  Infosys  2026      Q4     6374    1218      90758

In [1086]:
data_dict['Company_Financials'].sort_values( by = 'Revenue', ascending = False ).head()

       Financial_ID  Company  Year Quarter  Revenue  Profit  Employees
29205         29206  HCLTech  2021      Q3     9000     577      54520
46482         46483    Wipro  2024      Q2     9000     457     131498
98008         98009    Wipro  2021      Q3     9000     861     243738
55534         55535      TCS  2022      Q2     9000    1857     165982
79751         79752    Wipro  2019      Q3     9000     552     204409

##### 5. Sort `technologies` by `Popularity` descending.

In [1087]:
data_dict['Technologies'].head()

   Technology_ID  Company Technology  Project_ID  Popularity
0              1  HCLTech        SAP      153468       57.75
1              2    Wipro        SAP       48952       57.73
2              3  HCLTech      Azure      146403       78.35
3              4      TCS     Python       39073       75.26
4              5      TCS      Azure       50553       85.76

In [1088]:
data_dict['Technologies'].sort_values( by = 'Popularity', ascending = False ).head()

        Technology_ID  Company Technology  Project_ID  Popularity
76232           76233      TCS        SAP       58196       100.0
38032           38033  Infosys        AWS      153757       100.0
119121         119122      TCS     Python      161474       100.0
105442         105443  Infosys        AWS        3357       100.0
85034           85035  Infosys        AWS      157353       100.0

##### **Type B — `.head()` / `.nlargest()`**

##### 6. Find the top 5 highest-paid employees using `.nlargest()`.

In [1089]:
data_dict['Employees'].head()

   Employee_ID  Company   Department Role  Age  Salary    JoinDate
0            1    Wipro           AI   QA   50   91806  11-04-2020
1            2    Wipro      Finance   SE   21   14827  12-04-2020
2            3    Wipro      Finance   BA   49  121727  13-04-2020
3            4    Wipro  Engineering  SSE   43   88985  14-04-2020
4            5  Infosys      Finance   SE   25   35904  15-04-2020

In [1090]:
data_dict['Employees'].nlargest(5, 'Salary')

        Employee_ID  Company Department Role  Age  Salary    JoinDate
81995         81996    Wipro    Finance   DS   35  150000  09-10-2244
129810       129811    Wipro    Support   QA   26  150000  08-09-2375
241621       241622      TCS    Finance  SSE   45  150000  24-10-2681
20041         20042      TCS    Support  SSE   52  149998  23-02-2075
46759         46760  HCLTech    Support   DS   21  149998  19-04-2148

##### 7. Find the top 3 clients by `ContractValue`.

In [1091]:
data_dict['Clients'].head()

   Client_ID  Company    Industry Country  ContractValue
0          1    Wipro      Retail   India       39728043
1          2      TCS  Healthcare   India       41065784
2          3    Wipro  Healthcare   India       32180187
3          4      TCS  Healthcare  Canada        7905343
4          5  Infosys      Retail      UK       15392192

In [1092]:
data_dict['Clients'].nlargest(3,'ContractValue')

       Client_ID  Company       Industry  Country  ContractValue
88432      88433    Wipro  Manufacturing  Germany       49999295
44704      44705  Infosys  Manufacturing   Canada       49999084
70332      70333  Infosys        Telecom       UK       49998424

##### 8. Find the top 5 projects by `Budget`.

In [1093]:
data_dict['Projects'].head()

,Project_ID,Company,Client_ID,Employee_ID,Technology,Budget,Status
0,1,Wipro,32252,195820,Azure,8646817,In Progress
1,2,Wipro,21042,69871,Azure,6633547,On Hold
2,3,HCLTech,89295,148126,AWS,5647221,On Hold
3,4,Infosys,54119,115503,Java,7970162,On Hold
4,5,TCS,114709,100718,GCP,4313680,In Progress

In [1094]:
data_dict['Projects'].nlargest(5, 'Budget')

,Project_ID,Company,Client_ID,Employee_ID,Technology,Budget,Status
53884,53885,HCLTech,72801,230397,Azure,9999902,In Progress
32513,32514,Wipro,25174,143144,SAP,9999892,Completed
117146,117147,Wipro,4039,49372,Azure,9999770,On Hold
22244,22245,HCLTech,65861,119656,Java,9999724,On Hold
80257,80258,HCLTech,99498,186314,Java,9999704,On Hold

##### 9. Find the top 3 rows by `Revenue` in `financials`.

In [1095]:
data_dict['Company_Financials'].head()

   Financial_ID  Company  Year Quarter  Revenue  Profit  Employees
0             1      TCS  2015      Q3     4812     994      86579
1             2      TCS  2025      Q1     7712     210      57811
2             3      TCS  2018      Q2     1234    2378     102124
3             4  HCLTech  2018      Q4     5357     106     248916
4             5  Infosys  2026      Q4     6374    1218      90758

In [1096]:
data_dict['Company_Financials'].nlargest(3, 'Revenue')

       Financial_ID  Company  Year Quarter  Revenue  Profit  Employees
13479         13480      TCS  2021      Q3     9000     234     151837
18666         18667  HCLTech  2016      Q4     9000    1646      98913
29205         29206  HCLTech  2021      Q3     9000     577      54520

##### 10. Find the top 5 rows by `Popularity` in `technologies`.

In [1097]:
data_dict['Technologies'].head()

   Technology_ID  Company Technology  Project_ID  Popularity
0              1  HCLTech        SAP      153468       57.75
1              2    Wipro        SAP       48952       57.73
2              3  HCLTech      Azure      146403       78.35
3              4      TCS     Python       39073       75.26
4              5      TCS      Azure       50553       85.76

In [1098]:
data_dict['Technologies'].nlargest(5, 'Popularity')

       Technology_ID  Company Technology  Project_ID  Popularity
19293          19294    Wipro     Python      158484       100.0
36989          36990    Wipro        SAP      162284       100.0
38032          38033  Infosys        AWS      153757       100.0
44807          44808  Infosys        AWS       55895       100.0
53464          53465    Wipro        GCP      143095       100.0

##### **Type C — Multi-column sort**

##### 11. Sort `employees` by `Department` ascending, then `Salary` descending.

In [1099]:
data_dict['Employees'].head()

   Employee_ID  Company   Department Role  Age  Salary    JoinDate
0            1    Wipro           AI   QA   50   91806  11-04-2020
1            2    Wipro      Finance   SE   21   14827  12-04-2020
2            3    Wipro      Finance   BA   49  121727  13-04-2020
3            4    Wipro  Engineering  SSE   43   88985  14-04-2020
4            5  Infosys      Finance   SE   25   35904  15-04-2020

In [1100]:
data_dict['Employees'].sort_values(by=['Department', 'Salary'], ascending=[True, False]).head()

        Employee_ID  Company Department    Role  Age  Salary    JoinDate
94979         94980      TCS         AI  DevOps   37  149997  27-04-2280
114160       114161    Wipro         AI      SE   45  149996  02-11-2332
25808         25809  HCLTech         AI      BA   43  149986  08-12-2090
156249       156250  Infosys         AI      BA   21  149985  27-01-2448
108350       108351    Wipro         AI      DS   36  149983  06-12-2316

##### 12. Sort `clients` by `Industry` ascending, then `ContractValue` descending.

In [1101]:
data_dict['Clients'].head()

   Client_ID  Company    Industry Country  ContractValue
0          1    Wipro      Retail   India       39728043
1          2      TCS  Healthcare   India       41065784
2          3    Wipro  Healthcare   India       32180187
3          4      TCS  Healthcare  Canada        7905343
4          5  Infosys      Retail      UK       15392192

In [1102]:
data_dict['Clients'].sort_values(by=['Industry','ContractValue'],ascending=[True,False]).head()

       Client_ID  Company Industry Country  ContractValue
54195      54196  HCLTech  Banking   India       49997280
51887      51888      TCS  Banking      UK       49997145
98283      98284  Infosys  Banking      UK       49996725
52701      52702    Wipro  Banking  Canada       49993871
52463      52464  Infosys  Banking   India       49992681

##### 13. Sort `projects` by `Status` ascending, then `Budget` descending.

In [1103]:
data_dict['Projects'].head()

,Project_ID,Company,Client_ID,Employee_ID,Technology,Budget,Status
0,1,Wipro,32252,195820,Azure,8646817,In Progress
1,2,Wipro,21042,69871,Azure,6633547,On Hold
2,3,HCLTech,89295,148126,AWS,5647221,On Hold
3,4,Infosys,54119,115503,Java,7970162,On Hold
4,5,TCS,114709,100718,GCP,4313680,In Progress

In [1104]:
data_dict['Projects'].sort_values(by=['Status','Budget'],ascending=[True,False]).head()

,Project_ID,Company,Client_ID,Employee_ID,Technology,Budget,Status
32513,32514,Wipro,25174,143144,SAP,9999892,Completed
37306,37307,Wipro,93980,28632,AWS,9999590,Completed
159986,159987,HCLTech,55109,138762,Azure,9999459,Completed
76619,76620,TCS,77876,188274,SAP,9999306,Completed
84507,84508,Wipro,36866,67262,Python,9999073,Completed

##### 14. Sort `financials` by `Company` ascending, then `Year` descending.

In [1105]:
data_dict['Company_Financials'].head()

   Financial_ID  Company  Year Quarter  Revenue  Profit  Employees
0             1      TCS  2015      Q3     4812     994      86579
1             2      TCS  2025      Q1     7712     210      57811
2             3      TCS  2018      Q2     1234    2378     102124
3             4  HCLTech  2018      Q4     5357     106     248916
4             5  Infosys  2026      Q4     6374    1218      90758

In [1106]:
data_dict['Company_Financials'].sort_values(by=['Company','Year'],ascending=[True,False]).head()

     Financial_ID  Company  Year Quarter  Revenue  Profit  Employees
138           139  HCLTech  2026      Q3     7394    1195     181195
159           160  HCLTech  2026      Q4     7125     703     179847
211           212  HCLTech  2026      Q1     5512    1359     142181
329           330  HCLTech  2026      Q3     8580     148     146562
336           337  HCLTech  2026      Q1     3062    2204     104353

##### 15. Sort `offices` by `Country` ascending, then `City` ascending.

In [1107]:
data_dict['Office_Locations'].head()

   Office_ID  Company Country State       City  Employees
0          1    Wipro  Canada    KA       Pune      10757
1          2  HCLTech   India    TS       Pune       7143
2          3    Wipro      UK    TS    Chennai       8807
3          4  HCLTech  Canada    WB    Chennai       3058
4          5    Wipro  Canada    TN  Bengaluru       8998

In [1108]:
data_dict['Office_Locations'].sort_values(by=['Country','City'],ascending=[True,False]).head()

    Office_ID Company Country State  City  Employees
0           1   Wipro  Canada    KA  Pune      10757
49         50     TCS  Canada    TS  Pune      10264
72         73   Wipro  Canada    MH  Pune      13956
74         75     TCS  Canada    TN  Pune       2251
77         78   Wipro  Canada    KA  Pune       4098

##### **Type D — String methods (`.str`)**

In [1109]:
# Method	                            What it does
# .str.upper() / .str.lower()	        Convert case
# .str.len()	                        Character count of each string
# .str.strip()	                        Remove leading/trailing whitespace
# .str.replace('old', 'new')	        Replace substrings
# .str.contains('text')	                Boolean — does the string contain this?
# .str.split(',')	                    Split into a list
# .str.startswith() / .str.endswith()	Boolean checks
# .str.slice(0, 3) or [0:3]	            Substring
# .str.title()	                        Capitalize Each Word
# .str.cat(sep=', ')	                Join strings together
# .str.extract(r'(\d+)')	            Pull out text matching a regex pattern

##### 16. Convert all `Company` values in `clients` to uppercase using `.str.upper()`.

In [1110]:
data_dict['Clients'].head()

   Client_ID  Company    Industry Country  ContractValue
0          1    Wipro      Retail   India       39728043
1          2      TCS  Healthcare   India       41065784
2          3    Wipro  Healthcare   India       32180187
3          4      TCS  Healthcare  Canada        7905343
4          5  Infosys      Retail      UK       15392192

In [1111]:
data_dict['Clients']['Company'].str.upper()

0           WIPRO
1             TCS
2           WIPRO
3             TCS
4         INFOSYS
           ...
119995    HCLTECH
119996        TCS
119997      WIPRO
119998    INFOSYS
119999    INFOSYS
Name: Company, Length: 120000, dtype: str

##### 17. Create a new column with the character length of each `Role` in `employees`.

In [1112]:
data_dict['Employees'].head()

   Employee_ID  Company   Department Role  Age  Salary    JoinDate
0            1    Wipro           AI   QA   50   91806  11-04-2020
1            2    Wipro      Finance   SE   21   14827  12-04-2020
2            3    Wipro      Finance   BA   49  121727  13-04-2020
3            4    Wipro  Engineering  SSE   43   88985  14-04-2020
4            5  Infosys      Finance   SE   25   35904  15-04-2020

In [1113]:
data_dict['Employees']['Role_len'] = data_dict['Employees']['Role'].str.len()

In [1114]:
data_dict['Employees'].head()

   Employee_ID  Company   Department Role  Age  Salary    JoinDate  Role_len
0            1    Wipro           AI   QA   50   91806  11-04-2020         2
1            2    Wipro      Finance   SE   21   14827  12-04-2020         2
2            3    Wipro      Finance   BA   49  121727  13-04-2020         2
3            4    Wipro  Engineering  SSE   43   88985  14-04-2020         3
4            5  Infosys      Finance   SE   25   35904  15-04-2020         2

##### 18. Combine `City` and `Country` from `offices` into one column separated by a comma.

In [1115]:
data_dict['Office_Locations'].head()

   Office_ID  Company Country State       City  Employees
0          1    Wipro  Canada    KA       Pune      10757
1          2  HCLTech   India    TS       Pune       7143
2          3    Wipro      UK    TS    Chennai       8807
3          4  HCLTech  Canada    WB    Chennai       3058
4          5    Wipro  Canada    TN  Bengaluru       8998

In [1116]:
data_dict['Office_Locations']['City_and_Country'] = data_dict['Office_Locations']['City'].str.cat(data_dict['Office_Locations']['Country'], sep=', ')

In [1117]:
data_dict['Office_Locations']['City_and_Country']

0             Pune, Canada
1              Pune, India
2              Chennai, UK
3          Chennai, Canada
4        Bengaluru, Canada
               ...
99995       Bengaluru, USA
99996       Chennai, India
99997    Hyderabad, Canada
99998       Chennai, India
99999         Kolkata, USA
Name: City_and_Country, Length: 100000, dtype: str

##### 19. Extract the first 3 letters of each `Technology` name in `technologies`.

In [1118]:
data_dict['Technologies'].head()

   Technology_ID  Company Technology  Project_ID  Popularity
0              1  HCLTech        SAP      153468       57.75
1              2    Wipro        SAP       48952       57.73
2              3  HCLTech      Azure      146403       78.35
3              4      TCS     Python       39073       75.26
4              5      TCS      Azure       50553       85.76

In [1119]:
data_dict['Technologies']['Technology'].str.extract(r'(^.{3})')

# To extract the first 3 characters using regex, use ^
# {3} (where ^ means start of string, and .{3} means any 3 characters)

          0
0       SAP
1       SAP
2       Azu
3       Pyt
4       Azu
...     ...
149995  AWS
149996  AWS
149997  GCP
149998  Jav
149999  Azu

[150000 rows x 1 columns]

##### 20. Strip any leading/trailing whitespace from `Company` names using `.str.strip()`.

In [1120]:
data_dict['Clients'].head()

   Client_ID  Company    Industry Country  ContractValue
0          1    Wipro      Retail   India       39728043
1          2      TCS  Healthcare   India       41065784
2          3    Wipro  Healthcare   India       32180187
3          4      TCS  Healthcare  Canada        7905343
4          5  Infosys      Retail      UK       15392192

In [1121]:
data_dict['Clients']['Company'].str.strip()

0           Wipro
1             TCS
2           Wipro
3             TCS
4         Infosys
           ...
119995    HCLTech
119996        TCS
119997      Wipro
119998    Infosys
119999    Infosys
Name: Company, Length: 120000, dtype: str

In [1122]:
### Python

# ['Clients', 'Company_Financials', 'Employees', 'Office_Locations', 'Projects', 'Technologies']

# Method	                            What it does
# .str.upper() / .str.lower()	        Convert case
# .str.len()	                        Character count of each string
# .str.strip()	                        Remove leading/trailing whitespace
# .str.replace('old', 'new')	        Replace substrings
# .str.contains('text')	                Boolean — does the string contain this?
# .str.split(',')	                    Split into a list
# .str.startswith() / .str.endswith()	Boolean checks
# .str.slice(0, 3) or [0:3]	            Substring
# .str.title()	                        Capitalize Each Word
# .str.cat(sep=', ')	                Join strings together
# .str.extract(r'(\d+)')	            Pull out text matching a regex pattern

##### **Type A — Basic `.merge()` (2 DataFrames)**

In [1123]:
print(list(data_dict.keys()))

['Clients', 'Company_Financials', 'Employees', 'Office_Locations', 'Projects', 'Technologies']

##### 1. Merge `projects` and `clients` on `Client_ID` to add each client's `Company` name to the projects table.

In [1124]:
data_dict['Projects'].head()

,Project_ID,Company,Client_ID,Employee_ID,Technology,Budget,Status
0,1,Wipro,32252,195820,Azure,8646817,In Progress
1,2,Wipro,21042,69871,Azure,6633547,On Hold
2,3,HCLTech,89295,148126,AWS,5647221,On Hold
3,4,Infosys,54119,115503,Java,7970162,On Hold
4,5,TCS,114709,100718,GCP,4313680,In Progress

In [1125]:
data_dict_merge1 = data_dict['Clients'].merge(data_dict['Projects'][['Client_ID', 'Company']],
                   on='Client_ID',
                   how='left')

data_dict_merge1.head()

   Client_ID Company_x    Industry Country  ContractValue Company_y
0          1     Wipro      Retail   India       39728043     Wipro
1          2       TCS  Healthcare   India       41065784       NaN
2          3     Wipro  Healthcare   India       32180187   Infosys
3          4       TCS  Healthcare  Canada        7905343   HCLTech
4          4       TCS  Healthcare  Canada        7905343   HCLTech

##### 2. Merge `employees` and `projects` on `Employee_ID` to add each employee's `Role` to the projects table.

In [1126]:
data_dict_merge2 =  data_dict['Projects'].merge(data_dict['Employees'][['Employee_ID', 'Role']],
                    on='Employee_ID',
                    how='left')

data_dict_merge2.head()

,Project_ID,Company,Client_ID,Employee_ID,Technology,Budget,Status,Role
0,1,Wipro,32252,195820,Azure,8646817,In Progress,PM
1,2,Wipro,21042,69871,Azure,6633547,On Hold,PM
2,3,HCLTech,89295,148126,AWS,5647221,On Hold,DevOps
3,4,Infosys,54119,115503,Java,7970162,On Hold,SE
4,5,TCS,114709,100718,GCP,4313680,In Progress,DS

##### 3. Merge `financials` and `offices` on `Company` to see revenue alongside office city.

In [1127]:
company_revenue = data_dict['Company_Financials'].groupby('Company')['Revenue'].sum().reset_index()

data_dict_merge3 = data_dict['Office_Locations'].merge(company_revenue, on='Company', how='left')
data_dict_merge3.head()

,Office_ID,Company,Country,State,City,Employees,City_and_Country,Revenue
0,1,Wipro,Canada,KA,Pune,10757,"Pune, Canada",146888445
1,2,HCLTech,India,TS,Pune,7143,"Pune, India",145945545
2,3,Wipro,UK,TS,Chennai,8807,"Chennai, UK",146888445
3,4,HCLTech,Canada,WB,Chennai,3058,"Chennai, Canada",145945545
4,5,Wipro,Canada,TN,Bengaluru,8998,"Bengaluru, Canada",146888445

##### 4. Merge `projects` and `technologies` on `Project_ID` to see project status alongside technology.

In [1128]:
data_dict['Projects'].head()

,Project_ID,Company,Client_ID,Employee_ID,Technology,Budget,Status
0,1,Wipro,32252,195820,Azure,8646817,In Progress
1,2,Wipro,21042,69871,Azure,6633547,On Hold
2,3,HCLTech,89295,148126,AWS,5647221,On Hold
3,4,Infosys,54119,115503,Java,7970162,On Hold
4,5,TCS,114709,100718,GCP,4313680,In Progress

In [1129]:
data_dict_merge4 = data_dict['Technologies'].merge(data_dict['Projects'][['Project_ID', 'Technology']],
    on='Project_ID',
    how='left'
)

data_dict_merge4.head()

   Technology_ID  Company Technology_x  Project_ID  Popularity Technology_y
0              1  HCLTech          SAP      153468       57.75         Java
1              2    Wipro          SAP       48952       57.73         Java
2              3  HCLTech        Azure      146403       78.35         Java
3              4      TCS       Python       39073       75.26       Python
4              5      TCS        Azure       50553       85.76          GCP

##### 5. Merge `clients` and `financials` on `Company` to compare `ContractValue` to `Revenue`.

In [1130]:
data_dict['Company_Financials'].head()

   Financial_ID  Company  Year Quarter  Revenue  Profit  Employees
0             1      TCS  2015      Q3     4812     994      86579
1             2      TCS  2025      Q1     7712     210      57811
2             3      TCS  2018      Q2     1234    2378     102124
3             4  HCLTech  2018      Q4     5357     106     248916
4             5  Infosys  2026      Q4     6374    1218      90758

In [1131]:
print(data_dict['Clients'].columns.tolist())

['Client_ID', 'Company', 'Industry', 'Country', 'ContractValue']

In [1132]:
print(data_dict['Company_Financials']['Company'].duplicated().sum())
print(data_dict['Clients']['Company'].duplicated().sum())

119996
119996

In [1133]:
print(data_dict['Company_Financials'].shape)
print(data_dict['Clients'].shape)
print(data_dict['Company_Financials']['Company'].value_counts())
print(data_dict['Clients']['Company'].value_counts())

(120000, 7)
(120000, 5)
Company
TCS        30186
Wipro      30098
Infosys    29963
HCLTech    29753
Name: count, dtype: int64
Company
Infosys    30179
HCLTech    30052
Wipro      29928
TCS        29841
Name: count, dtype: int64

In [1134]:
# Aggregate contract value per company (choose the summary that fits your analysis)
clients_agg = (
    data_dict['Clients']
    .groupby('Company', as_index=False)['ContractValue']
    .sum()  # or .mean(), depending on what you want to compare
)

data_dict_merge5 = data_dict['Company_Financials'].merge(
    clients_agg,
    on='Company',
    how='left'
)

data_dict_merge5.head()

,Financial_ID,Company,Year,Quarter,Revenue,Profit,Employees,ContractValue
0,1,TCS,2015,Q3,4812,994,86579,752415545056
1,2,TCS,2025,Q1,7712,210,57811,752415545056
2,3,TCS,2018,Q2,1234,2378,102124,752415545056
3,4,HCLTech,2018,Q4,5357,106,248916,746722909774
4,5,Infosys,2026,Q4,6374,1218,90758,753146001192

##### **Type B — Merge + filter**

##### 6. Merge `projects` and `clients`, then filter to only clients in the `'Retail'` industry.

##### 7. Merge `employees` and `projects`, then filter to only projects with `Status == 'In Progress'`.

##### 8. Merge `offices` and `financials`, then filter to only offices in `'India'`.

##### 9. Merge `projects` and `technologies`, then filter to only `Technology == 'Azure'`.

##### 10. Merge `clients` and `projects`, then filter to only projects with `Budget > 5000000`.

In [1135]:
# **Type C — Merge + groupby**
# 11. Merge `projects` and `clients`, then find total `Budget` per client `Industry`.
# 12. Merge `employees` and `projects`, then count projects per employee `Department`.
# 13. Merge `offices` and `financials`, then find average `Revenue` per office `Country`.
# 14. Merge `projects` and `technologies`, then find average `Popularity` per project `Status`.
# 15. Merge `clients` and `projects`, then find average `Budget` per client `Country`.

# **Type D — `how='left'` + finding unmatched rows**
# 16. Left-merge `clients` with `projects` to find clients with no associated project (`Project_ID` is `NaN`).
# 17. Left-merge `employees` with `projects` to find employees not assigned to any project.
# 18. Left-merge `financials` with `offices` (on Company) to find companies with financials but no office listed.
# 19. Left-merge `technologies` with `projects` to find technology entries with no matching project.
# 20. Left-merge `offices` with `financials` (on Company) to find offices with no matching financial record.

In [1136]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus
import os, glob
import pandas as pd

# --- 1. Connection (set up once) ---
server = r"LAPTOP-A70F1ENF\SHIVASQLEXPRESS"
database = "P_Big4_India"
driver = "ODBC Driver 17 for SQL Server"

params = quote_plus(
    f"DRIVER={{{driver}}};"
    f"SERVER={server};"
    f"DATABASE={database};"
    f"Trusted_Connection=yes;"
)
engine = create_engine(f"mssql+pyodbc:///?odbc_connect={params}")

# --- 2. Load all CSVs into a dict ---
folder_path = r"C:\Users\Shiva Thakur\OneDrive\Desktop\Github\Practice\Daily Python\E_Big4_India"
data_dict = {
    os.path.splitext(os.path.basename(f))[0]: pd.read_csv(f)
    for f in glob.glob(os.path.join(folder_path, "*.csv"))
}

# --- 3. Push each DataFrame to its own table ---
for table_name, df in data_dict.items():
    df.to_sql(table_name, engine, if_exists="replace", index=False)
    print(f"Loaded table: {table_name} ({df.shape[0]} rows)")

# --- 4. Sanity check ---
for table_name in data_dict.keys():
    print(f"\n--- {table_name} ---")
    print(pd.read_sql(f"SELECT TOP 5 * FROM [{table_name}];", engine))