In [184]:
import ast
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt


%matplotlib inline

In [185]:
from pathlib import Path

folder = Path(r"C:\Users\Shiva Thakur\OneDrive\Desktop\Github\Projects\Python\E_Big4_India")

data_dict = {f.stem: pd.read_csv(f) for f in folder.glob("*.csv")}

In [186]:
clients = data_dict['Clients']

print("Shape:", clients.shape)
clients.head()

Shape: (120000, 5)

   Client_ID  Company    Industry Country  ContractValue
0          1    Wipro      Retail   India       39728043
1          2      TCS  Healthcare   India       41065784
2          3    Wipro  Healthcare   India       32180187
3          4      TCS  Healthcare  Canada        7905343
4          5  Infosys      Retail      UK       15392192

##### 1. Find employees whose `Salary` is above `employees['Salary'].mean()`.

In [187]:
print(list(data_dict['Employees'].columns))

['Employee_ID', 'Company', 'Department', 'Role', 'Age', 'Salary', 'JoinDate']

In [188]:
avg_salary = data_dict['Employees']['Salary'].mean()

high_earners = data_dict['Employees'][data_dict['Employees']['Salary'] > avg_salary]

high_earners.head()

   Employee_ID  Company   Department Role  Age  Salary    JoinDate
0            1    Wipro           AI   QA   50   91806  11-04-2020
2            3    Wipro      Finance   BA   49  121727  13-04-2020
3            4    Wipro  Engineering  SSE   43   88985  14-04-2020
5            6  HCLTech        Cloud  SSE   44  144114  16-04-2020
6            7      TCS           HR   DS   44  128945  17-04-2020

##### 2. Find clients whose `ContractValue` is above `clients['ContractValue'].mean()`.

In [189]:
print(list(data_dict['Clients'].columns))

['Client_ID', 'Company', 'Industry', 'Country', 'ContractValue']

In [190]:
avg_contractvalue = data_dict['Clients']['ContractValue'].mean()

high_contractvalue = data_dict['Clients'][data_dict['Clients']['ContractValue'] > avg_contractvalue]

high_contractvalue.head()

   Client_ID  Company    Industry Country  ContractValue
0          1    Wipro      Retail   India       39728043
1          2      TCS  Healthcare   India       41065784
2          3    Wipro  Healthcare   India       32180187
6          7    Wipro      Retail      UK       39845758
7          8  HCLTech     Telecom      UK       25774510

##### 3. Find projects whose `Budget` is above `projects['Budget'].mean()`.

In [191]:
print(list(data_dict['Projects'].columns))

['Project_ID', 'Company', 'Client_ID', 'Employee_ID', 'Technology', 'Budget', 'Status']

In [192]:
avg_budget = data_dict['Projects']['Budget'].mean()

high_budget = data_dict['Projects'][data_dict['Projects']['Budget'] > avg_budget]

high_budget.head()

,Project_ID,Company,Client_ID,Employee_ID,Technology,Budget,Status
0,1,Wipro,32252,195820,Azure,8646817,In Progress
1,2,Wipro,21042,69871,Azure,6633547,On Hold
2,3,HCLTech,89295,148126,AWS,5647221,On Hold
3,4,Infosys,54119,115503,Java,7970162,On Hold
5,6,TCS,91805,24244,AWS,9438406,Completed

##### 4. Find financial records where `Revenue` is above `financials['Revenue'].mean()`.

In [193]:
print(list(data_dict['Company_Financials'].columns))

['Financial_ID', 'Company', 'Year', 'Quarter', 'Revenue', 'Profit', 'Employees']

In [194]:
avg_revenue = data_dict['Company_Financials']['Revenue'].mean()

high_revenue = data_dict['Company_Financials'][data_dict['Company_Financials']['Revenue'] > avg_revenue]

high_revenue.head()

   Financial_ID  Company  Year Quarter  Revenue  Profit  Employees
1             2      TCS  2025      Q1     7712     210      57811
3             4  HCLTech  2018      Q4     5357     106     248916
4             5  Infosys  2026      Q4     6374    1218      90758
7             8      TCS  2021      Q1     5603    1561     201349
9            10      TCS  2018      Q1     7027    1218     168858

##### 5. Find technologies where `Popularity` is above `technologies['Popularity'].mean()`.

In [195]:
print(list(data_dict['Technologies'].columns))

['Technology_ID', 'Company', 'Technology', 'Project_ID', 'Popularity']

In [196]:
avg_popularity = data_dict['Technologies']['Popularity'].mean()

high_popularity = data_dict['Technologies'][data_dict['Technologies']['Popularity'] > avg_popularity]

high_popularity.head()

   Technology_ID  Company Technology  Project_ID  Popularity
2              3  HCLTech      Azure      146403       78.35
3              4      TCS     Python       39073       75.26
4              5      TCS      Azure       50553       85.76
5              6      TCS     Python       78218       99.57
6              7  Infosys     Python      145439       99.08

##### **Type B — GroupBy + filter (pandas' HAVING equivalent)**

##### 6. Find departments where average `Salary` exceeds 60000 (`.groupby().filter()` or `.groupby().mean()` + boolean mask).

In [197]:
avg_salary_by_dept = data_dict['Employees'].groupby('Department', as_index=False)['Salary'].mean()

high_salary_depts = avg_salary_by_dept[avg_salary_by_dept['Salary'] > 60000]

high_salary_depts

    Department        Salary
0           AI  79439.986241
1        Cloud  78825.292326
2  Engineering  78711.194318
3      Finance  78867.216524
4           HR  78975.945153
5           IT  78833.816166
6        Sales  78837.073820
7      Support  78676.077096

##### 7. Find industries where total `ContractValue` exceeds 100000000.

In [198]:
print(list(data_dict['Clients'].columns))

['Client_ID', 'Company', 'Industry', 'Country', 'ContractValue']

In [199]:
total_ctcvalue_by_in = data_dict['Clients'].groupby('Industry', as_index=False)['ContractValue'].sum()

high_ctcvalue = total_ctcvalue_by_in[total_ctcvalue_by_in['ContractValue'] > 100000000]

high_ctcvalue

        Industry  ContractValue
0        Banking   599032568528
1     Healthcare   600337613772
2  Manufacturing   603192574026
3         Retail   599373926642
4        Telecom   597507023455

In [200]:
print(total_ctcvalue_by_in.sort_values('ContractValue', ascending=False))

        Industry  ContractValue
2  Manufacturing   603192574026
1     Healthcare   600337613772
3         Retail   599373926642
0        Banking   599032568528
4        Telecom   597507023455

##### 8. Find project statuses where average `Budget` exceeds 5000000.

In [201]:
print(list(data_dict['Projects'].columns))

['Project_ID', 'Company', 'Client_ID', 'Employee_ID', 'Technology', 'Budget', 'Status']

In [202]:
avg_budget = data_dict['Projects'].groupby('Status',as_index=False)['Budget'].mean()

high_budget = avg_budget[avg_budget['Budget'] > 5000000]

high_budget

        Status        Budget
0    Completed  5.032317e+06
1  In Progress  5.032368e+06
2      On Hold  5.014446e+06

##### 9. Find companies where total `Revenue` exceeds 50000.

In [203]:
print(list(data_dict['Company_Financials'].columns))

['Financial_ID', 'Company', 'Year', 'Quarter', 'Revenue', 'Profit', 'Employees']

In [204]:
total_rev = data_dict['Company_Financials'].groupby('Company',as_index=False)['Revenue'].sum()

high_rev = total_rev[total_rev['Revenue'] > 50000]

high_rev

   Company    Revenue
0  HCLTech  145945545
1  Infosys  147142230
2      TCS  148172596
3    Wipro  146888445

##### 10. Find technologies where average `Popularity` exceeds 50.

In [205]:
print(list(data_dict.keys()))

['Clients', 'Company_Financials', 'Employees', 'Office_Locations', 'Projects', 'Technologies']

In [206]:
print(list(data_dict['Technologies'].columns))

['Technology_ID', 'Company', 'Technology', 'Project_ID', 'Popularity']

In [207]:
avg_popularity = data_dict['Technologies'].groupby('Technology',as_index=False)['Popularity'].mean()

high_popularity = avg_popularity[avg_popularity['Popularity'] > 50]

high_popularity

  Technology  Popularity
0        AWS   74.988675
1      Azure   74.957781
2        GCP   74.961102
3       Java   74.878793
4     Python   74.860119
5        SAP   74.989803

##### **Type C — `.apply()` / `np.where()` for categorization**

##### 11. Create a column labeling each employee `'Senior'` if `Age > 40`, else `'Junior'`.

In [208]:
print(list(data_dict['Employees'].columns))

['Employee_ID', 'Company', 'Department', 'Role', 'Age', 'Salary', 'JoinDate']

In [209]:
# This updates the 'Employees' DataFrame inside your data_dict
data_dict["Employees"]["Status"] = np.where(
    data_dict["Employees"]["Age"] > 40, 
    "Senior",
    "Junior")

data_dict['Employees']

,Employee_ID,Company,Department,Role,Age,Salary,JoinDate,Status
0,1,Wipro,AI,QA,50,91806,11-04-2020,Senior
1,2,Wipro,Finance,SE,21,14827,12-04-2020,Junior
2,3,Wipro,Finance,BA,49,121727,13-04-2020,Senior
3,4,Wipro,Engineering,SSE,43,88985,14-04-2020,Senior
4,5,Infosys,Finance,SE,25,35904,15-04-2020,Junior
...,...,...,...,...,...,...,...,...
249995,249996,Wipro,Finance,DevOps,39,29369,28-09-2704,Junior
249996,249997,Infosys,Support,QA,58,65865,29-09-2704,Senior
249997,249998,Infosys,Finance,QA,34,48007,30-09-2704,Junior
249998,249999,HCLTech,Engineering,SE,43,65756,01-10-2704,Senior
249999,250000,TCS,Sales,QA,49,113592,02-10-2704,Senior

##### 12. Create a column labeling each client `'High Value'` if `ContractValue > 20000000`, else `'Standard'`.

In [210]:
print(list(data_dict['Clients'].columns))

['Client_ID', 'Company', 'Industry', 'Country', 'ContractValue']

In [211]:
data_dict['Clients']['Value status'] = np.where(
    data_dict['Clients']['ContractValue'] > 20000000,
    'High Value',
    'Standard')

data_dict['Clients'].head()

   Client_ID  Company    Industry Country  ContractValue Value status
0          1    Wipro      Retail   India       39728043   High Value
1          2      TCS  Healthcare   India       41065784   High Value
2          3    Wipro  Healthcare   India       32180187   High Value
3          4      TCS  Healthcare  Canada        7905343     Standard
4          5  Infosys      Retail      UK       15392192     Standard

##### 13. Create a column labeling each project `'Big Budget'` if `Budget > 5000000`, else `'Small Budget'`.

In [212]:
print(list(data_dict['Projects'].columns))

['Project_ID', 'Company', 'Client_ID', 'Employee_ID', 'Technology', 'Budget', 'Status']

In [213]:
data_dict['Projects']['Budget_Category'] = np.where(
    data_dict['Projects']['Budget'] > 5_000_000,
    'Big Budget',
    'Small Budget')

data_dict['Projects'].head()

,Project_ID,Company,Client_ID,Employee_ID,Technology,Budget,Status,Budget_Category
0,1,Wipro,32252,195820,Azure,8646817,In Progress,Big Budget
1,2,Wipro,21042,69871,Azure,6633547,On Hold,Big Budget
2,3,HCLTech,89295,148126,AWS,5647221,On Hold,Big Budget
3,4,Infosys,54119,115503,Java,7970162,On Hold,Big Budget
4,5,TCS,114709,100718,GCP,4313680,In Progress,Small Budget

##### 14. Create a column labeling each financial record `'Profitable'` if `Profit > 0`, else `'Loss'`.

In [214]:
print(list(data_dict['Company_Financials'].columns))

['Financial_ID', 'Company', 'Year', 'Quarter', 'Revenue', 'Profit', 'Employees']

In [215]:
data_dict['Company_Financials']['Financial Record'] = np.where(
    data_dict['Company_Financials']['Profit'] > 0,
    'Profit',
    'Loss')

data_dict['Company_Financials'].head()

,Financial_ID,Company,Year,Quarter,Revenue,Profit,Employees,Financial Record
0,1,TCS,2015,Q3,4812,994,86579,Profit
1,2,TCS,2025,Q1,7712,210,57811,Profit
2,3,TCS,2018,Q2,1234,2378,102124,Profit
3,4,HCLTech,2018,Q4,5357,106,248916,Profit
4,5,Infosys,2026,Q4,6374,1218,90758,Profit

##### 15. Create a column labeling each technology `'Popular'` if `Popularity > 50`, else `'Niche'`.

In [216]:
print(list(data_dict['Technologies'].columns))

['Technology_ID', 'Company', 'Technology', 'Project_ID', 'Popularity']

In [217]:
data_dict['Technologies']['Tech Popularity'] = np.where(
    data_dict['Technologies']['Popularity'] > 50,
    'Popular',
    'Niche'
)

data_dict['Technologies'].head()

   Technology_ID  Company Technology  Project_ID  Popularity Tech Popularity
0              1  HCLTech        SAP      153468       57.75         Popular
1              2    Wipro        SAP       48952       57.73         Popular
2              3  HCLTech      Azure      146403       78.35         Popular
3              4      TCS     Python       39073       75.26         Popular
4              5      TCS      Azure       50553       85.76         Popular

##### **Type D — `.transform()` for per-group comparison**

##### 16. Find employees earning more than their department's average salary using `.groupby('Department')['Salary'].transform('mean')`.

In [218]:
employees_above_avg = data_dict['Employees'][
    data_dict['Employees']['Salary'] >
    data_dict['Employees'].groupby('Department')['Salary'].transform('mean')]

employees_above_avg.head()

   Employee_ID  Company   Department Role  Age  Salary    JoinDate  Status
0            1    Wipro           AI   QA   50   91806  11-04-2020  Senior
2            3    Wipro      Finance   BA   49  121727  13-04-2020  Senior
3            4    Wipro  Engineering  SSE   43   88985  14-04-2020  Senior
5            6  HCLTech        Cloud  SSE   44  144114  16-04-2020  Senior
6            7      TCS           HR   DS   44  128945  17-04-2020  Senior

##### 17. Find clients whose `ContractValue` is above their industry's average using `.transform()`.

In [219]:
print(list(data_dict['Clients'].columns))

['Client_ID', 'Company', 'Industry', 'Country', 'ContractValue', 'Value status']

In [220]:
industry_avg = data_dict['Clients'].groupby("Industry")["ContractValue"].transform("mean")

above_industry_average = data_dict['Clients'][data_dict['Clients']["ContractValue"] > industry_avg]

above_industry_average.head()

   Client_ID  Company    Industry Country  ContractValue Value status
0          1    Wipro      Retail   India       39728043   High Value
1          2      TCS  Healthcare   India       41065784   High Value
2          3    Wipro  Healthcare   India       32180187   High Value
6          7    Wipro      Retail      UK       39845758   High Value
7          8  HCLTech     Telecom      UK       25774510   High Value

##### 18. Find projects whose `Budget` is above their status group's average using `.transform()`.

In [221]:
print(list(data_dict['Projects'].columns))

['Project_ID', 'Company', 'Client_ID', 'Employee_ID', 'Technology', 'Budget', 'Status', 'Budget_Category']

In [222]:
status_group_avg = data_dict['Projects'].groupby('Status')['Budget'].transform("mean")

Status_above_group = data_dict['Projects'][data_dict['Projects']['Budget'] > status_group_avg]

Status_above_group.head()

,Project_ID,Company,Client_ID,Employee_ID,Technology,Budget,Status,Budget_Category
0,1,Wipro,32252,195820,Azure,8646817,In Progress,Big Budget
1,2,Wipro,21042,69871,Azure,6633547,On Hold,Big Budget
2,3,HCLTech,89295,148126,AWS,5647221,On Hold,Big Budget
3,4,Infosys,54119,115503,Java,7970162,On Hold,Big Budget
5,6,TCS,91805,24244,AWS,9438406,Completed,Big Budget

##### 19. Find financial records above their company's average revenue using `.transform()`.

In [223]:
print(list(data_dict['Company_Financials'].columns))

['Financial_ID', 'Company', 'Year', 'Quarter', 'Revenue', 'Profit', 'Employees', 'Financial Record']

In [224]:
avg_revenue = data_dict['Company_Financials'].groupby('Company')['Revenue'].transform('mean')

above_avg = data_dict['Company_Financials'][data_dict['Company_Financials']['Revenue'] > avg_revenue]

above_avg.head()

,Financial_ID,Company,Year,Quarter,Revenue,Profit,Employees,Financial Record
1,2,TCS,2025,Q1,7712,210,57811,Profit
3,4,HCLTech,2018,Q4,5357,106,248916,Profit
4,5,Infosys,2026,Q4,6374,1218,90758,Profit
7,8,TCS,2021,Q1,5603,1561,201349,Profit
9,10,TCS,2018,Q1,7027,1218,168858,Profit

##### 20. Find technologies above their company's average popularity using `.transform()`.

In [225]:
print(list(data_dict['Technologies'].columns))

['Technology_ID', 'Company', 'Technology', 'Project_ID', 'Popularity', 'Tech Popularity']

In [226]:
avg_popularity1 = data_dict['Technologies'].groupby('Company')['Popularity'].transform('mean')

above_avg_popularity = data_dict['Technologies'][data_dict['Technologies']['Popularity'] > avg_popularity1]

above_avg_popularity.head()

   Technology_ID  Company Technology  Project_ID  Popularity Tech Popularity
2              3  HCLTech      Azure      146403       78.35         Popular
3              4      TCS     Python       39073       75.26         Popular
4              5      TCS      Azure       50553       85.76         Popular
5              6      TCS     Python       78218       99.57         Popular
6              7  Infosys     Python      145439       99.08         Popular

##### **Type A — `.rank()` within groups**

##### 1. Rank employees within each `Department` by `Salary` descending using `.groupby()['Salary'].rank()`.

In [227]:
print(list(data_dict['Employees'].columns))

['Employee_ID', 'Company', 'Department', 'Role', 'Age', 'Salary', 'JoinDate', 'Status']

In [228]:
data_dict['Employees']['Salary_Rank'] = (
    data_dict['Employees']
    .groupby('Department')['Salary']
    .rank(ascending=False, method='dense')
)

data_dict['Employees'].head()

,Employee_ID,Company,Department,Role,Age,Salary,JoinDate,Status,Salary_Rank
0,1,Wipro,AI,QA,50,91806,11-04-2020,Senior,11691.0
1,2,Wipro,Finance,SE,21,14827,12-04-2020,Junior,26798.0
2,3,Wipro,Finance,BA,49,121727,13-04-2020,Senior,5598.0
3,4,Wipro,Engineering,SSE,43,88985,14-04-2020,Senior,12099.0
4,5,Infosys,Finance,SE,25,35904,15-04-2020,Junior,22605.0

##### 2. Rank clients within each `Industry` by `ContractValue` descending.

In [229]:
print(list(data_dict['Clients'].columns))

['Client_ID', 'Company', 'Industry', 'Country', 'ContractValue', 'Value status']

In [230]:
data_dict['Clients']['Client_Rank'] = (
    data_dict['Clients']
    .groupby('Industry')['ContractValue']
    .rank(ascending=False, method='dense'))

data_dict['Clients'].head()

,Client_ID,Company,Industry,Country,ContractValue,Value status,Client_Rank
0,1,Wipro,Retail,India,39728043,High Value,4841.0
1,2,TCS,Healthcare,India,41065784,High Value,4254.0
2,3,Wipro,Healthcare,India,32180187,High Value,8500.0
3,4,TCS,Healthcare,Canada,7905343,Standard,20244.0
4,5,Infosys,Retail,UK,15392192,Standard,16656.0

##### 3. Rank projects within each `Status` by `Budget` descending.

In [231]:
print(list(data_dict['Projects'].columns))

['Project_ID', 'Company', 'Client_ID', 'Employee_ID', 'Technology', 'Budget', 'Status', 'Budget_Category']

In [232]:
data_dict['Projects']['Project_Rank'] = (
    data_dict['Projects']
    .groupby('Status')['Budget']
    .rank(ascending=False,method='dense'))

data_dict['Projects'].head()

,Project_ID,Company,Client_ID,Employee_ID,Technology,Budget,Status,Budget_Category,Project_Rank
0,1,Wipro,32252,195820,Azure,8646817,In Progress,Big Budget,8142.0
1,2,Wipro,21042,69871,Azure,6633547,On Hold,Big Budget,20146.0
2,3,HCLTech,89295,148126,AWS,5647221,On Hold,Big Budget,26074.0
3,4,Infosys,54119,115503,Java,7970162,On Hold,Big Budget,12164.0
4,5,TCS,114709,100718,GCP,4313680,In Progress,Small Budget,34200.0

##### 4. Rank financial records within each `Company` by `Revenue` descending.

In [233]:
data_dict['Company_Financials']['Financial_Rank'] = (
    data_dict['Company_Financials']
    .groupby('Company')['Revenue']
    .rank(ascending=False,method='dense'))

data_dict['Company_Financials'].head()

,Financial_ID,Company,Year,Quarter,Revenue,Profit,Employees,Financial Record,Financial_Rank
0,1,TCS,2015,Q3,4812,994,86579,Profit,4076.0
1,2,TCS,2025,Q1,7712,210,57811,Profit,1251.0
2,3,TCS,2018,Q2,1234,2378,102124,Profit,7559.0
3,4,HCLTech,2018,Q4,5357,106,248916,Profit,3543.0
4,5,Infosys,2026,Q4,6374,1218,90758,Profit,2547.0

##### 5. Rank technologies within each `Company` by `Popularity` descending.

In [234]:
data_dict['Technologies']['Technology_Rank'] = (
    data_dict['Technologies']
    .groupby('Company')['Popularity']
    .rank(ascending=False,method='dense'))

data_dict['Technologies'].head()

,Technology_ID,Company,Technology,Project_ID,Popularity,Tech Popularity,Technology_Rank
0,1,HCLTech,SAP,153468,57.75,Popular,4222.0
1,2,Wipro,SAP,48952,57.73,Popular,4227.0
2,3,HCLTech,Azure,146403,78.35,Popular,2162.0
3,4,TCS,Python,39073,75.26,Popular,2475.0
4,5,TCS,Azure,50553,85.76,Popular,1425.0

##### **Type B — Top N per group (`.groupby().apply()` or `sort_values` + `groupby().head()`)**

##### 6. Top 2 highest-paid employees in each Department

In [235]:
top2_employees = (
    data_dict['Employees']
    .sort_values('Salary', ascending=False)
    .groupby('Department')
    .head(2)
)

top2_employees.head()

,Employee_ID,Company,Department,Role,Age,Salary,JoinDate,Status,Salary_Rank
241621,241622,TCS,Finance,SSE,45,150000,24-10-2681,Senior,1.0
81995,81996,Wipro,Finance,DS,35,150000,09-10-2244,Junior,1.0
129810,129811,Wipro,Support,QA,26,150000,08-09-2375,Junior,1.0
182728,182729,TCS,HR,QA,48,149998,27-07-2520,Senior,1.0
46759,46760,HCLTech,Support,DS,21,149998,19-04-2148,Junior,2.0

##### 7. Top 2 highest-value clients in each Industry

In [236]:
top2_clients = (
    data_dict['Clients']
    .sort_values('ContractValue', ascending=False)
    .groupby('Industry')
    .head(2)
)

top2_clients.head()

,Client_ID,Company,Industry,Country,ContractValue,Value status,Client_Rank
88432,88433,Wipro,Manufacturing,Germany,49999295,High Value,1.0
44704,44705,Infosys,Manufacturing,Canada,49999084,High Value,2.0
70332,70333,Infosys,Telecom,UK,49998424,High Value,1.0
54195,54196,HCLTech,Banking,India,49997280,High Value,1.0
51887,51888,TCS,Banking,UK,49997145,High Value,2.0

##### 8. Top 2 highest-budget projects in each Status

In [237]:
top2_projects = (
    data_dict['Projects']
    .sort_values('Budget', ascending=False)
    .groupby('Status')
    .head(2)
)

top2_projects.head()

,Project_ID,Company,Client_ID,Employee_ID,Technology,Budget,Status,Budget_Category,Project_Rank
53884,53885,HCLTech,72801,230397,Azure,9999902,In Progress,Big Budget,1.0
32513,32514,Wipro,25174,143144,SAP,9999892,Completed,Big Budget,1.0
117146,117147,Wipro,4039,49372,Azure,9999770,On Hold,Big Budget,1.0
22244,22245,HCLTech,65861,119656,Java,9999724,On Hold,Big Budget,2.0
103198,103199,HCLTech,93727,14599,Python,9999595,In Progress,Big Budget,2.0

##### 9. Top 2 highest-revenue records for each Company

In [238]:
top2_financials = (
    data_dict['Company_Financials']
    .sort_values('Revenue', ascending=False)
    .groupby('Company')
    .head(2)
)

top2_financials.head()

,Financial_ID,Company,Year,Quarter,Revenue,Profit,Employees,Financial Record,Financial_Rank
29205,29206,HCLTech,2021,Q3,9000,577,54520,Profit,1.0
46482,46483,Wipro,2024,Q2,9000,457,131498,Profit,1.0
98008,98009,Wipro,2021,Q3,9000,861,243738,Profit,1.0
55534,55535,TCS,2022,Q2,9000,1857,165982,Profit,1.0
18666,18667,HCLTech,2016,Q4,9000,1646,98913,Profit,1.0

##### 10. Top 2 most popular technologies for each Company

In [239]:
top2_tech = (
    data_dict['Technologies']
    .sort_values('Popularity', ascending=False)
    .groupby('Company')
    .head(2)
)

top2_tech.head()

,Technology_ID,Company,Technology,Project_ID,Popularity,Tech Popularity,Technology_Rank
76232,76233,TCS,SAP,58196,100.0,Popular,1.0
38032,38033,Infosys,AWS,153757,100.0,Popular,1.0
119121,119122,TCS,Python,161474,100.0,Popular,1.0
105442,105443,Infosys,AWS,3357,100.0,Popular,1.0
82088,82089,HCLTech,Azure,138117,100.0,Popular,1.0

##### 11. Find the top 3 highest-salary employees in each `Department`.

In [240]:
top3_emp = (
    data_dict['Employees']
    .sort_values('Salary', ascending=False)
    .groupby('Department')
    .head(3))

top3_emp.head()

,Employee_ID,Company,Department,Role,Age,Salary,JoinDate,Status,Salary_Rank
241621,241622,TCS,Finance,SSE,45,150000,24-10-2681,Senior,1.0
81995,81996,Wipro,Finance,DS,35,150000,09-10-2244,Junior,1.0
129810,129811,Wipro,Support,QA,26,150000,08-09-2375,Junior,1.0
182728,182729,TCS,HR,QA,48,149998,27-07-2520,Senior,1.0
46759,46760,HCLTech,Support,DS,21,149998,19-04-2148,Junior,2.0

##### 12. Find the top 2 highest-employee-count offices in each `Country`.

In [241]:
print(list(data_dict['Office_Locations'].columns))

['Office_ID', 'Company', 'Country', 'State', 'City', 'Employees']

In [242]:
top2_empcount = (
    data_dict['Office_Locations']
    .sort_values('Employees', ascending=False)
    .groupby('Country')
    .head(2)
)

top2_empcount.head()

       Office_ID  Company  Country State       City  Employees
42520      42521      TCS       UK    TS    Kolkata      15000
24352      24353  HCLTech       UK    TN  Hyderabad      15000
62968      62969  HCLTech  Germany    TS  Hyderabad      15000
24932      24933    Wipro    India    MH  Hyderabad      14999
91414      91415      TCS   Canada    TS       Pune      14999

##### 13. Find the top 3 highest-contract-value clients in each `Country`.

In [243]:
print(list(data_dict['Clients'].columns))

['Client_ID', 'Company', 'Industry', 'Country', 'ContractValue', 'Value status', 'Client_Rank']

In [244]:
top3_contractvalue = (
    data_dict['Clients']
    .sort_values('ContractValue', ascending=False)
    .groupby('Country')
    .head(3)
)

top3_contractvalue.head()

,Client_ID,Company,Industry,Country,ContractValue,Value status,Client_Rank
88432,88433,Wipro,Manufacturing,Germany,49999295,High Value,1.0
44704,44705,Infosys,Manufacturing,Canada,49999084,High Value,2.0
70332,70333,Infosys,Telecom,UK,49998424,High Value,1.0
85134,85135,Infosys,Manufacturing,Germany,49997360,High Value,3.0
54195,54196,HCLTech,Banking,India,49997280,High Value,1.0

##### 14. Find the top 2 most recent financial records (by `Year`, then `Quarter`) for each `Company`.

In [245]:
top2_financialecord = (
    data_dict['Company_Financials']
    .sort_values('Year', ascending=False)
    .groupby('Company')
    .head(2)
)

top2_financialecord.head()

,Financial_ID,Company,Year,Quarter,Revenue,Profit,Employees,Financial Record,Financial_Rank
34,35,Infosys,2026,Q4,4781,2017,156708,Profit,4083.0
73681,73682,TCS,2026,Q1,3931,1168,132763,Profit,4933.0
73696,73697,Wipro,2026,Q4,7700,1837,131259,Profit,1269.0
73698,73699,Wipro,2026,Q3,3074,2078,107874,Profit,5771.0
19955,19956,HCLTech,2026,Q3,7628,310,111679,Profit,1332.0

##### **Type C — `.cumsum()` running totals**

##### 11. Calculate a running total of `Salary` ordered by `Employee_ID`.

In [246]:
data_dict['Employees'] = data_dict['Employees'].sort_values('Employee_ID')
data_dict['Employees']['running_total'] = data_dict['Employees']['Salary'].cumsum()

data_dict['Employees'].head()

,Employee_ID,Company,Department,Role,Age,Salary,JoinDate,Status,Salary_Rank,running_total
0,1,Wipro,AI,QA,50,91806,11-04-2020,Senior,11691.0,91806
1,2,Wipro,Finance,SE,21,14827,12-04-2020,Junior,26798.0,106633
2,3,Wipro,Finance,BA,49,121727,13-04-2020,Senior,5598.0,228360
3,4,Wipro,Engineering,SSE,43,88985,14-04-2020,Senior,12099.0,317345
4,5,Infosys,Finance,SE,25,35904,15-04-2020,Junior,22605.0,353249

##### 12. Calculate a running total of `ContractValue` ordered by `Client_ID`.

In [247]:
data_dict['Clients'] = data_dict['Clients'].sort_values('Client_ID')
data_dict['Clients']['running_Clients'] = data_dict['Clients']['ContractValue'].cumsum()

data_dict['Clients'].head()

,Client_ID,Company,Industry,Country,ContractValue,Value status,Client_Rank,running_Clients
0,1,Wipro,Retail,India,39728043,High Value,4841.0,39728043
1,2,TCS,Healthcare,India,41065784,High Value,4254.0,80793827
2,3,Wipro,Healthcare,India,32180187,High Value,8500.0,112974014
3,4,TCS,Healthcare,Canada,7905343,Standard,20244.0,120879357
4,5,Infosys,Retail,UK,15392192,Standard,16656.0,136271549

##### 13. Calculate a running total of `Budget` ordered by `Project_ID`.

In [248]:
print(list(data_dict.keys()))

['Clients', 'Company_Financials', 'Employees', 'Office_Locations', 'Projects', 'Technologies']

In [249]:
print(list(data_dict['Projects'].columns))

['Project_ID', 'Company', 'Client_ID', 'Employee_ID', 'Technology', 'Budget', 'Status', 'Budget_Category', 'Project_Rank']

In [250]:
data_dict['Projects'] = data_dict['Projects'].sort_values('Project_ID')
data_dict['Projects']['running_Budget'] = data_dict['Projects']['Budget'].cumsum()

data_dict['Projects'].head()

,Project_ID,Company,Client_ID,Employee_ID,Technology,Budget,Status,Budget_Category,Project_Rank,running_Budget
0,1,Wipro,32252,195820,Azure,8646817,In Progress,Big Budget,8142.0,8646817
1,2,Wipro,21042,69871,Azure,6633547,On Hold,Big Budget,20146.0,15280364
2,3,HCLTech,89295,148126,AWS,5647221,On Hold,Big Budget,26074.0,20927585
3,4,Infosys,54119,115503,Java,7970162,On Hold,Big Budget,12164.0,28897747
4,5,TCS,114709,100718,GCP,4313680,In Progress,Small Budget,34200.0,33211427

##### 14. Calculate a running total of `Revenue` per `Company`, ordered by `Year`.

In [251]:
print(list(data_dict.keys()))

['Clients', 'Company_Financials', 'Employees', 'Office_Locations', 'Projects', 'Technologies']

In [252]:
data_dict['Company_Financials'] = data_dict['Company_Financials'].sort_values('Year')

data_dict['Company_Financials']['running_Revenue'] = data_dict['Company_Financials']['Revenue'].cumsum()

data_dict['Company_Financials'].head()

,Financial_ID,Company,Year,Quarter,Revenue,Profit,Employees,Financial Record,Financial_Rank,running_Revenue
119932,119933,Wipro,2015,Q3,2346,1744,107502,Profit,6472.0,2346
119921,119922,Wipro,2015,Q4,2358,1690,151602,Profit,6460.0,4704
100290,100291,HCLTech,2015,Q3,8026,1026,141909,Profit,947.0,12730
60292,60293,TCS,2015,Q1,5601,654,172341,Profit,3312.0,18331
60288,60289,Infosys,2015,Q3,6594,2380,191979,Profit,2332.0,24925

##### 15. Calculate a running total of `Popularity` ordered by `Technology_ID`.

In [253]:
print(list(data_dict['Technologies'].columns))

['Technology_ID', 'Company', 'Technology', 'Project_ID', 'Popularity', 'Tech Popularity', 'Technology_Rank']

In [254]:
data_dict['Technologies'] = data_dict['Technologies'].sort_values('Technology_ID')

data_dict['Technologies']['running_Popularity'] = data_dict['Technologies']['Popularity'].cumsum()

data_dict['Technologies'].head()

,Technology_ID,Company,Technology,Project_ID,Popularity,Tech Popularity,Technology_Rank,running_Popularity
0,1,HCLTech,SAP,153468,57.75,Popular,4222.0,57.75
1,2,Wipro,SAP,48952,57.73,Popular,4227.0,115.48
2,3,HCLTech,Azure,146403,78.35,Popular,2162.0,193.83
3,4,TCS,Python,39073,75.26,Popular,2475.0,269.09
4,5,TCS,Azure,50553,85.76,Popular,1425.0,354.85

##### **Type D — Combining all 6 CSVs / reshaping**

##### 16. Load all 6 CSVs from the folder into a dictionary using glob (like your earlier script), then print the shape of each.

In [255]:
from pathlib import Path
import glob
import os

folder = Path(r"C:\Users\Shiva Thakur\OneDrive\Desktop\Github\Projects\Python\E_Big4_India")

data_dict = {}
csv_files = glob.glob(str(folder / "*.csv"))

for file in csv_files:
    table_name = os.path.splitext(os.path.basename(file))[0]
    data_dict[table_name] = pd.read_csv(file)

for name, df in data_dict.items():
    print(f"{name}: {df.shape}")

Clients: (120000, 5)
Company_Financials: (120000, 7)
Employees: (250000, 7)
Office_Locations: (100000, 6)
Projects: (180000, 7)
Technologies: (150000, 5)

##### 17. Merge `employees`, `projects`, and `clients` together into one combined DataFrame (two merges).

In [256]:
merged = data_dict['Projects'].merge(
    data_dict['Employees'],
    on='Employee_ID',
    how='left',
    validate='many_to_one'
)

merged = merged.merge(
    data_dict['Clients'],
    on='Client_ID',
    how='left',
    validate='many_to_one'
)

merged.head()

,Project_ID,Company_x,Client_ID,Employee_ID,Technology,Budget,Status,Company_y,Department,Role,Age,Salary,JoinDate,Company,Industry,Country,ContractValue
0,1,Wipro,32252,195820,Azure,8646817,In Progress,Wipro,Finance,PM,25,118913,30-05-2556,HCLTech,Healthcare,UK,37353571
1,2,Wipro,21042,69871,Azure,6633547,On Hold,Infosys,Finance,PM,59,20220,30-07-2211,TCS,Telecom,Canada,46381259
2,3,HCLTech,89295,148126,AWS,5647221,On Hold,TCS,IT,DevOps,32,81709,30-10-2425,HCLTech,Healthcare,USA,35518385
3,4,Infosys,54119,115503,Java,7970162,On Hold,HCLTech,Finance,SE,25,30883,06-07-2336,Infosys,Healthcare,Germany,26194180
4,5,TCS,114709,100718,GCP,4313680,In Progress,Infosys,Sales,DS,35,140011,12-01-2296,Infosys,Healthcare,UK,27992839

##### 18. Use `pd.concat()` to stack `clients` and a filtered subset of `clients` back together and check the row count doubled correctly.

In [257]:
clients = data_dict['Clients']
retail_subset = clients[clients['Industry'] == 'Retail']

stacked = pd.concat([clients, retail_subset], ignore_index=True)

print(f"Original: {len(clients)}")
print(f"Subset: {len(retail_subset)}")
print(f"Stacked: {len(stacked)}")
print(f"Expected: {len(clients) + len(retail_subset)}")

Original: 120000
Subset: 24018
Stacked: 144018
Expected: 144018

##### 19. Pivot `financials` so that `Year` becomes columns and `Revenue` is the value, with `Company` as the index (`pivot_table`).

In [258]:
pivoted = data_dict['Company_Financials'].pivot_table(
    index='Company',
    columns='Year',
    values='Revenue',
    aggfunc='sum'
)

pivoted

Year,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026
Company,,,,,,,,,,,,
HCLTech,11898518,12424025,12498743,12463034,12146212,12091885,12099609,12157225,12376800,11573313,12055704,12160477
Infosys,11705980,12418990,12818645,12430425,12437211,12608971,11816439,12167806,12080381,12326908,12004737,12325737
TCS,12302887,12494177,12382242,12639403,11765647,12237475,12353646,12302145,12318007,12328211,12512586,12536170
Wipro,12540600,12316883,12095621,12168459,12180713,12226403,12602110,12015207,12228230,12235161,12128384,12150674

##### 20. Show each technology's `Popularity` as a percentage of its company's total popularity using `.transform('sum')`.

In [259]:
data_dict['Technologies']['company_total_popularity'] = (
    data_dict['Technologies'].groupby('Company')['Popularity'].transform('sum')
)

data_dict['Technologies']['pct_of_company_total'] = (
    data_dict['Technologies']['Popularity'] / data_dict['Technologies']['company_total_popularity'] * 100
)

data_dict['Technologies'].head()

,Technology_ID,Company,Technology,Project_ID,Popularity,company_total_popularity,pct_of_company_total
0,1,HCLTech,SAP,153468,57.75,2820104.46,0.002048
1,2,Wipro,SAP,48952,57.73,2805411.36,0.002058
2,3,HCLTech,Azure,146403,78.35,2820104.46,0.002778
3,4,TCS,Python,39073,75.26,2812901.63,0.002676
4,5,TCS,Azure,50553,85.76,2812901.63,0.003049

##### Type A — Merge + groupby combo (CTE equivalent)

In [260]:
# 1. Average Salary per Department, merged back onto employees
dept_avg_salary = data_dict['Employees'].groupby('Department', as_index=False)['Salary'].mean()
dept_avg_salary = dept_avg_salary.rename(columns={'Salary': 'dept_avg_salary'})
data_dict['Employees'] = data_dict['Employees'].merge(dept_avg_salary, on='Department', how='left')

data_dict['Employees'].head()

,Employee_ID,Company,Department,Role,Age,Salary,JoinDate,dept_avg_salary
0,1,Wipro,AI,QA,50,91806,11-04-2020,79439.986241
1,2,Wipro,Finance,SE,21,14827,12-04-2020,78867.216524
2,3,Wipro,Finance,BA,49,121727,13-04-2020,78867.216524
3,4,Wipro,Engineering,SSE,43,88985,14-04-2020,78711.194318
4,5,Infosys,Finance,SE,25,35904,15-04-2020,78867.216524

In [261]:
# 2. Total ContractValue per Industry, merged back onto clients
industry_total_cv = data_dict['Clients'].groupby('Industry', as_index=False)['ContractValue'].sum()
industry_total_cv = industry_total_cv.rename(columns={'ContractValue': 'industry_total_contractvalue'})
data_dict['Clients'] = data_dict['Clients'].merge(industry_total_cv, on='Industry', how='left')

In [262]:
# 3. Average Budget per Status, merged back onto projects
status_avg_budget = data_dict['Projects'].groupby('Status', as_index=False)['Budget'].mean()
status_avg_budget = status_avg_budget.rename(columns={'Budget': 'status_avg_budget'})
data_dict['Projects'] = data_dict['Projects'].merge(status_avg_budget, on='Status', how='left')

In [263]:
# 4. Total Revenue per Company, merged back onto financials
company_total_revenue = data_dict['Company_Financials'].groupby('Company', as_index=False)['Revenue'].sum()
company_total_revenue = company_total_revenue.rename(columns={'Revenue': 'company_total_revenue'})
data_dict['Company_Financials'] = data_dict['Company_Financials'].merge(company_total_revenue, on='Company', how='left')

In [264]:
# 5. Average Popularity per Company, merged back onto technologies
company_avg_popularity = data_dict['Technologies'].groupby('Company', as_index=False)['Popularity'].mean()
company_avg_popularity = company_avg_popularity.rename(columns={'Popularity': 'company_avg_popularity'})
data_dict['Technologies'] = data_dict['Technologies'].merge(company_avg_popularity, on='Company', how='left')

##### Type B — Filtering with .transform() (above-average per group)

In [265]:
# 6. Employees earning more than 20% above their department's average salary
dept_avg = data_dict['Employees'].groupby('Department')['Salary'].transform('mean')
high_earners = data_dict['Employees'][data_dict['Employees']['Salary'] > dept_avg * 1.2]

In [266]:
# 7. Clients whose ContractValue is more than 20% above their industry's average
industry_avg = data_dict['Clients'].groupby('Industry')['ContractValue'].transform('mean')
high_value_clients = data_dict['Clients'][data_dict['Clients']['ContractValue'] > industry_avg * 1.2]

In [267]:
# 8. Projects whose Budget is more than 20% above their status group's average
status_avg = data_dict['Projects'].groupby('Status')['Budget'].transform('mean')
high_budget_projects = data_dict['Projects'][data_dict['Projects']['Budget'] > status_avg * 1.2]

In [268]:
# 9. Financial records more than 20% above their company's average revenue
company_avg = data_dict['Company_Financials'].groupby('Company')['Revenue'].transform('mean')
high_revenue_records = data_dict['Company_Financials'][data_dict['Company_Financials']['Revenue'] > company_avg * 1.2]

In [269]:
# 10. Technologies more than 20% above their company's average popularity
tech_company_avg = data_dict['Technologies'].groupby('Company')['Popularity'].transform('mean')
high_popularity_tech = data_dict['Technologies'][data_dict['Technologies']['Popularity'] > tech_company_avg * 1.2]

##### Type C — Date handling (pd.to_datetime)

In [270]:
data_dict['Employees']['JoinDate'] = pd.to_datetime(
    data_dict['Employees']['JoinDate'],
    format='%d-%m-%Y'
)

In [271]:
# 12. Extract the year into a new column
data_dict['Employees']['JoinYear'] = data_dict['Employees']['JoinDate'].dt.year

In [272]:
# 13. Tenure in years (today minus JoinDate)
today = pd.Timestamp.now()
data_dict['Employees']['tenure_years'] = (today - data_dict['Employees']['JoinDate']).dt.days / 365.25

In [273]:
# 14. Earliest and latest JoinDate
earliest = data_dict['Employees']['JoinDate'].min()
latest = data_dict['Employees']['JoinDate'].max()
print(f"Earliest: {earliest}, Latest: {latest}")

Earliest: 2020-04-11 00:00:00, Latest: 2704-10-02 00:00:00

In [274]:
# 15. Count employees joined per year
joins_per_year = data_dict['Employees']['JoinDate'].dt.year.value_counts().sort_index()
print(joins_per_year)

JoinDate
2020    265
2021    365
2022    365
2023    365
2024    366
       ...
2700    365
2701    365
2702    365
2703    365
2704    276
Name: count, Length: 685, dtype: int64

In [275]:
# 12. Extract the year into a new column
data_dict['Employees']['JoinYear'] = data_dict['Employees']['JoinDate'].dt.year

In [276]:

# 13. Tenure in years (today minus JoinDate)
today = pd.Timestamp.now()
data_dict['Employees']['tenure_years'] = (today - data_dict['Employees']['JoinDate']).dt.days / 365.25

In [277]:
# 14. Earliest and latest JoinDate
earliest = data_dict['Employees']['JoinDate'].min()
latest = data_dict['Employees']['JoinDate'].max()
print(f"Earliest: {earliest}, Latest: {latest}")

Earliest: 2020-04-11 00:00:00, Latest: 2704-10-02 00:00:00

In [278]:
# 15. Count employees joined per year
joins_per_year = data_dict['Employees']['JoinDate'].dt.year.value_counts().sort_index()
print(joins_per_year)

JoinDate
2020    265
2021    365
2022    365
2023    365
2024    366
       ...
2700    365
2701    365
2702    365
2703    365
2704    276
Name: count, Length: 685, dtype: int64

In [ ]:
##### Type D — Combo: cleaning + visualization

In [ ]:
import matplotlib.pyplot as plt

# 16. Check for inconsistent Department spellings, standardize casing
print(data_dict['Employees']['Department'].unique())
data_dict['Employees']['Department'] = data_dict['Employees']['Department'].str.strip().str.title()
print(data_dict['Employees']['Department'].unique())

In [ ]:
# 17. Merge clients + projects, sum Budget per client, plot top 10
merged_cp = data_dict['Projects'].merge(
    data_dict['Clients'], on='Client_ID', how='left', validate='many_to_one'
)
budget_per_client = merged_cp.groupby('Company_y')['Budget'].sum().sort_values(ascending=False).head(10)
budget_per_client.plot(kind='bar', title='Top 10 Clients by Total Budget')
plt.ylabel('Total Budget')
plt.tight_layout()
plt.show()

In [ ]:
# 18. Bar chart of average Salary per Department
avg_salary_dept = data_dict['Employees'].groupby('Department')['Salary'].mean().sort_values(ascending=False)
avg_salary_dept.plot(kind='bar', title='Average Salary per Department')
plt.ylabel('Average Salary')
plt.tight_layout()
plt.show()

In [ ]:
# 19. Line chart of total Revenue per Year (across all companies)
revenue_per_year = data_dict['Company_Financials'].groupby('Year')['Revenue'].sum()
revenue_per_year.plot(kind='line', marker='o', title='Total Revenue per Year')
plt.ylabel('Total Revenue')
plt.tight_layout()
plt.show()

In [ ]:
# 20. Summary DataFrame: per Company — total Revenue, employee count, avg project Budget — export to CSV
revenue_summary = data_dict['Company_Financials'].groupby('Company', as_index=False)['Revenue'].sum()
emp_count = data_dict['Employees'].groupby('Company', as_index=False)['Employee_ID'].count().rename(columns={'Employee_ID': 'employee_count'})
budget_summary = data_dict['Projects'].groupby('Company', as_index=False)['Budget'].mean().rename(columns={'Budget': 'avg_project_budget'})

summary = revenue_summary.merge(emp_count, on='Company', how='left').merge(budget_summary, on='Company', how='left')
summary.to_csv('company_summary.csv', index=False)
summary