In [146]:
import ast
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

In [147]:
from pathlib import Path

folder = Path(r"C:\Users\Shiva Thakur\OneDrive\Desktop\Github\Projects\Python\E_Big4_India")

data_dict = {f.stem: pd.read_csv(f) for f in folder.glob("*.csv")}

In [148]:
clients = data_dict['Clients']

print("Shape:", clients.shape)
clients.head()

Shape: (120000, 5)

   Client_ID  Company    Industry Country  ContractValue
0          1    Wipro      Retail   India       39728043
1          2      TCS  Healthcare   India       41065784
2          3    Wipro  Healthcare   India       32180187
3          4      TCS  Healthcare  Canada        7905343
4          5  Infosys      Retail      UK       15392192

##### 1. Find employees whose `Salary` is above `employees['Salary'].mean()`.

In [149]:
print(list(data_dict['Employees'].columns))

['Employee_ID', 'Company', 'Department', 'Role', 'Age', 'Salary', 'JoinDate']

In [150]:
avg_salary = data_dict['Employees']['Salary'].mean()

high_earners = data_dict['Employees'][data_dict['Employees']['Salary'] > avg_salary]

high_earners.head()

   Employee_ID  Company   Department Role  Age  Salary    JoinDate
0            1    Wipro           AI   QA   50   91806  11-04-2020
2            3    Wipro      Finance   BA   49  121727  13-04-2020
3            4    Wipro  Engineering  SSE   43   88985  14-04-2020
5            6  HCLTech        Cloud  SSE   44  144114  16-04-2020
6            7      TCS           HR   DS   44  128945  17-04-2020

##### 2. Find clients whose `ContractValue` is above `clients['ContractValue'].mean()`.

In [151]:
print(list(data_dict['Clients'].columns))

['Client_ID', 'Company', 'Industry', 'Country', 'ContractValue']

In [152]:
avg_contractvalue = data_dict['Clients']['ContractValue'].mean()

high_contractvalue = data_dict['Clients'][data_dict['Clients']['ContractValue'] > avg_contractvalue]

high_contractvalue.head()

   Client_ID  Company    Industry Country  ContractValue
0          1    Wipro      Retail   India       39728043
1          2      TCS  Healthcare   India       41065784
2          3    Wipro  Healthcare   India       32180187
6          7    Wipro      Retail      UK       39845758
7          8  HCLTech     Telecom      UK       25774510

##### 3. Find projects whose `Budget` is above `projects['Budget'].mean()`.

In [153]:
print(list(data_dict['Projects'].columns))

['Project_ID', 'Company', 'Client_ID', 'Employee_ID', 'Technology', 'Budget', 'Status']

In [154]:
avg_budget = data_dict['Projects']['Budget'].mean()

high_budget = data_dict['Projects'][data_dict['Projects']['Budget'] > avg_budget]

high_budget.head()

,Project_ID,Company,Client_ID,Employee_ID,Technology,Budget,Status
0,1,Wipro,32252,195820,Azure,8646817,In Progress
1,2,Wipro,21042,69871,Azure,6633547,On Hold
2,3,HCLTech,89295,148126,AWS,5647221,On Hold
3,4,Infosys,54119,115503,Java,7970162,On Hold
5,6,TCS,91805,24244,AWS,9438406,Completed

##### 4. Find financial records where `Revenue` is above `financials['Revenue'].mean()`.

In [155]:
print(list(data_dict['Company_Financials'].columns))

['Financial_ID', 'Company', 'Year', 'Quarter', 'Revenue', 'Profit', 'Employees']

In [156]:
avg_revenue = data_dict['Company_Financials']['Revenue'].mean()

high_revenue = data_dict['Company_Financials'][data_dict['Company_Financials']['Revenue'] > avg_revenue]

high_revenue.head()

   Financial_ID  Company  Year Quarter  Revenue  Profit  Employees
1             2      TCS  2025      Q1     7712     210      57811
3             4  HCLTech  2018      Q4     5357     106     248916
4             5  Infosys  2026      Q4     6374    1218      90758
7             8      TCS  2021      Q1     5603    1561     201349
9            10      TCS  2018      Q1     7027    1218     168858

##### 5. Find technologies where `Popularity` is above `technologies['Popularity'].mean()`.

In [157]:
print(list(data_dict['Technologies'].columns))

['Technology_ID', 'Company', 'Technology', 'Project_ID', 'Popularity']

In [158]:
avg_popularity = data_dict['Technologies']['Popularity'].mean()

high_popularity = data_dict['Technologies'][data_dict['Technologies']['Popularity'] > avg_popularity]

high_popularity.head()

   Technology_ID  Company Technology  Project_ID  Popularity
2              3  HCLTech      Azure      146403       78.35
3              4      TCS     Python       39073       75.26
4              5      TCS      Azure       50553       85.76
5              6      TCS     Python       78218       99.57
6              7  Infosys     Python      145439       99.08

##### **Type B — GroupBy + filter (pandas' HAVING equivalent)**

##### 6. Find departments where average `Salary` exceeds 60000 (`.groupby().filter()` or `.groupby().mean()` + boolean mask).

In [159]:
avg_salary_by_dept = data_dict['Employees'].groupby('Department', as_index=False)['Salary'].mean()

high_salary_depts = avg_salary_by_dept[avg_salary_by_dept['Salary'] > 60000]

high_salary_depts

    Department        Salary
0           AI  79439.986241
1        Cloud  78825.292326
2  Engineering  78711.194318
3      Finance  78867.216524
4           HR  78975.945153
5           IT  78833.816166
6        Sales  78837.073820
7      Support  78676.077096

##### 7. Find industries where total `ContractValue` exceeds 100000000.

In [160]:
print(list(data_dict['Clients'].columns))

['Client_ID', 'Company', 'Industry', 'Country', 'ContractValue']

In [161]:
total_ctcvalue_by_in = data_dict['Clients'].groupby('Industry', as_index=False)['ContractValue'].sum()

high_ctcvalue = total_ctcvalue_by_in[total_ctcvalue_by_in['ContractValue'] > 100000000]

high_ctcvalue

        Industry  ContractValue
0        Banking   599032568528
1     Healthcare   600337613772
2  Manufacturing   603192574026
3         Retail   599373926642
4        Telecom   597507023455

In [162]:
print(total_ctcvalue_by_in.sort_values('ContractValue', ascending=False))

        Industry  ContractValue
2  Manufacturing   603192574026
1     Healthcare   600337613772
3         Retail   599373926642
0        Banking   599032568528
4        Telecom   597507023455

##### 8. Find project statuses where average `Budget` exceeds 5000000.

In [163]:
print(list(data_dict['Projects'].columns))

['Project_ID', 'Company', 'Client_ID', 'Employee_ID', 'Technology', 'Budget', 'Status']

In [164]:
avg_budget = data_dict['Projects'].groupby('Status',as_index=False)['Budget'].mean()

high_budget = avg_budget[avg_budget['Budget'] > 5000000]

high_budget

        Status        Budget
0    Completed  5.032317e+06
1  In Progress  5.032368e+06
2      On Hold  5.014446e+06

##### 9. Find companies where total `Revenue` exceeds 50000.

In [165]:
print(list(data_dict['Company_Financials'].columns))

['Financial_ID', 'Company', 'Year', 'Quarter', 'Revenue', 'Profit', 'Employees']

In [166]:
total_rev = data_dict['Company_Financials'].groupby('Company',as_index=False)['Revenue'].sum()

high_rev = total_rev[total_rev['Revenue'] > 50000]

high_rev

   Company    Revenue
0  HCLTech  145945545
1  Infosys  147142230
2      TCS  148172596
3    Wipro  146888445

##### 10. Find technologies where average `Popularity` exceeds 50.

In [167]:
print(list(data_dict.keys()))

['Clients', 'Company_Financials', 'Employees', 'Office_Locations', 'Projects', 'Technologies']

In [168]:
print(list(data_dict['Technologies'].columns))

['Technology_ID', 'Company', 'Technology', 'Project_ID', 'Popularity']

In [169]:
avg_popularity = data_dict['Technologies'].groupby('Technology',as_index=False)['Popularity'].mean()

high_popularity = avg_popularity[avg_popularity['Popularity'] > 50]

high_popularity

  Technology  Popularity
0        AWS   74.988675
1      Azure   74.957781
2        GCP   74.961102
3       Java   74.878793
4     Python   74.860119
5        SAP   74.989803

##### **Type C — `.apply()` / `np.where()` for categorization**

##### 11. Create a column labeling each employee `'Senior'` if `Age > 40`, else `'Junior'`.

In [170]:
print(list(data_dict['Employees'].columns))

['Employee_ID', 'Company', 'Department', 'Role', 'Age', 'Salary', 'JoinDate']

In [171]:
# This updates the 'Employees' DataFrame inside your data_dict
data_dict["Employees"]["Status"] = np.where(
    data_dict["Employees"]["Age"] > 40, 
    "Senior",
    "Junior")

data_dict['Employees']

,Employee_ID,Company,Department,Role,Age,Salary,JoinDate,Status
0,1,Wipro,AI,QA,50,91806,11-04-2020,Senior
1,2,Wipro,Finance,SE,21,14827,12-04-2020,Junior
2,3,Wipro,Finance,BA,49,121727,13-04-2020,Senior
3,4,Wipro,Engineering,SSE,43,88985,14-04-2020,Senior
4,5,Infosys,Finance,SE,25,35904,15-04-2020,Junior
...,...,...,...,...,...,...,...,...
249995,249996,Wipro,Finance,DevOps,39,29369,28-09-2704,Junior
249996,249997,Infosys,Support,QA,58,65865,29-09-2704,Senior
249997,249998,Infosys,Finance,QA,34,48007,30-09-2704,Junior
249998,249999,HCLTech,Engineering,SE,43,65756,01-10-2704,Senior
249999,250000,TCS,Sales,QA,49,113592,02-10-2704,Senior

##### 12. Create a column labeling each client `'High Value'` if `ContractValue > 20000000`, else `'Standard'`.

In [172]:
print(list(data_dict['Clients'].columns))

['Client_ID', 'Company', 'Industry', 'Country', 'ContractValue']

In [173]:
data_dict['Clients']['Value status'] = np.where(
    data_dict['Clients']['ContractValue'] > 20000000,
    'High Value',
    'Standard')

data_dict['Clients'].head()

   Client_ID  Company    Industry Country  ContractValue Value status
0          1    Wipro      Retail   India       39728043   High Value
1          2      TCS  Healthcare   India       41065784   High Value
2          3    Wipro  Healthcare   India       32180187   High Value
3          4      TCS  Healthcare  Canada        7905343     Standard
4          5  Infosys      Retail      UK       15392192     Standard

##### 13. Create a column labeling each project `'Big Budget'` if `Budget > 5000000`, else `'Small Budget'`.

In [174]:
print(list(data_dict['Projects'].columns))

['Project_ID', 'Company', 'Client_ID', 'Employee_ID', 'Technology', 'Budget', 'Status']

In [175]:
data_dict['Projects']['Budget_Category'] = np.where(
    data_dict['Projects']['Budget'] > 5_000_000,
    'Big Budget',
    'Small Budget')

data_dict['Projects'].head()

,Project_ID,Company,Client_ID,Employee_ID,Technology,Budget,Status,Budget_Category
0,1,Wipro,32252,195820,Azure,8646817,In Progress,Big Budget
1,2,Wipro,21042,69871,Azure,6633547,On Hold,Big Budget
2,3,HCLTech,89295,148126,AWS,5647221,On Hold,Big Budget
3,4,Infosys,54119,115503,Java,7970162,On Hold,Big Budget
4,5,TCS,114709,100718,GCP,4313680,In Progress,Small Budget

##### 14. Create a column labeling each financial record `'Profitable'` if `Profit > 0`, else `'Loss'`.

In [176]:
print(list(data_dict['Company_Financials'].columns))

['Financial_ID', 'Company', 'Year', 'Quarter', 'Revenue', 'Profit', 'Employees']

In [177]:
data_dict['Company_Financials']['Financial Record'] = np.where(
    data_dict['Company_Financials']['Profit'] > 0,
    'Profit',
    'Loss')

data_dict['Company_Financials'].head()

,Financial_ID,Company,Year,Quarter,Revenue,Profit,Employees,Financial Record
0,1,TCS,2015,Q3,4812,994,86579,Profit
1,2,TCS,2025,Q1,7712,210,57811,Profit
2,3,TCS,2018,Q2,1234,2378,102124,Profit
3,4,HCLTech,2018,Q4,5357,106,248916,Profit
4,5,Infosys,2026,Q4,6374,1218,90758,Profit

##### 15. Create a column labeling each technology `'Popular'` if `Popularity > 50`, else `'Niche'`.

In [178]:
print(list(data_dict['Technologies'].columns))

['Technology_ID', 'Company', 'Technology', 'Project_ID', 'Popularity']

In [179]:
data_dict['Technologies']['Tech Popularity'] = np.where(
    data_dict['Technologies']['Popularity'] > 50,
    'Popular',
    'Niche'
)

data_dict['Technologies'].head()

   Technology_ID  Company Technology  Project_ID  Popularity Tech Popularity
0              1  HCLTech        SAP      153468       57.75         Popular
1              2    Wipro        SAP       48952       57.73         Popular
2              3  HCLTech      Azure      146403       78.35         Popular
3              4      TCS     Python       39073       75.26         Popular
4              5      TCS      Azure       50553       85.76         Popular

##### **Type D — `.transform()` for per-group comparison**

##### 16. Find employees earning more than their department's average salary using `.groupby('Department')['Salary'].transform('mean')`.

In [180]:
employees_above_avg = data_dict['Employees'][
    data_dict['Employees']['Salary'] >
    data_dict['Employees'].groupby('Department')['Salary'].transform('mean')]

employees_above_avg.head()

   Employee_ID  Company   Department Role  Age  Salary    JoinDate  Status
0            1    Wipro           AI   QA   50   91806  11-04-2020  Senior
2            3    Wipro      Finance   BA   49  121727  13-04-2020  Senior
3            4    Wipro  Engineering  SSE   43   88985  14-04-2020  Senior
5            6  HCLTech        Cloud  SSE   44  144114  16-04-2020  Senior
6            7      TCS           HR   DS   44  128945  17-04-2020  Senior

##### 17. Find clients whose `ContractValue` is above their industry's average using `.transform()`.

##### 18. Find projects whose `Budget` is above their status group's average using `.transform()`.

##### 19. Find financial records above their company's average revenue using `.transform()`.

##### 20. Find technologies above their company's average popularity using `.transform()`.

In [181]:
## ['Clients', 'Company_Financials', 'Employees', 'Office_Locations', 'Projects', 'Technologies']

##### **Type A — `.rank()` within groups**
##### 1. Rank employees within each `Department` by `Salary` descending using `.groupby()['Salary'].rank()`.
##### 2. Rank clients within each `Industry` by `ContractValue` descending.
##### 3. Rank projects within each `Status` by `Budget` descending.
##### 4. Rank financial records within each `Company` by `Revenue` descending.
##### 5. Rank technologies within each `Company` by `Popularity` descending.

##### **Type B — Top N per group (`.groupby().apply()` or `sort_values` + `groupby().head()`)**
##### 6. Find the top 2 highest-paid employees in each `Department`.
##### 7. Find the top 2 highest-value clients in each `Industry`.
##### 8. Find the top 2 highest-budget projects in each `Status`.
##### 9. Find the top 2 highest-revenue records for each `Company`.
##### 10. Find the top 2 most popular technologies for each `Company`.

##### **Type C — `.cumsum()` running totals**
##### 11. Calculate a running total of `Salary` ordered by `Employee_ID`.
##### 12. Calculate a running total of `ContractValue` ordered by `Client_ID`.
##### 13. Calculate a running total of `Budget` ordered by `Project_ID`.
##### 14. Calculate a running total of `Revenue` per `Company`, ordered by `Year`.
##### 15. Calculate a running total of `Popularity` ordered by `Technology_ID`.

##### **Type D — Combining all 6 CSVs / reshaping**
##### 16. Load all 6 CSVs from the folder into a dictionary using glob (like your earlier script), then print the shape of each.
##### 17. Merge `employees`, `projects`, and `clients` together into one combined DataFrame (two merges).
##### 18. Use `pd.concat()` to stack `clients` and a filtered subset of `clients` back together and check the row count doubled correctly.
##### 19. Pivot `financials` so that `Year` becomes columns and `Revenue` is the value, with `Company` as the index (`pivot_table`).
##### 20. Show each technology's `Popularity` as a percentage of its company's total popularity using `.transform('sum')`.