In [148]:
import ast
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

In [149]:
from pathlib import Path

folder = Path(r"C:\Users\Shiva Thakur\OneDrive\Desktop\Github\Projects\Python\E_Big4_India")

data_dict = {f.stem: pd.read_csv(f) for f in folder.glob("*.csv")}

In [150]:
clients = data_dict['Clients']

print("Shape:", clients.shape)
clients.head()

Shape: (120000, 5)

   Client_ID  Company    Industry Country  ContractValue
0          1    Wipro      Retail   India       39728043
1          2      TCS  Healthcare   India       41065784
2          3    Wipro  Healthcare   India       32180187
3          4      TCS  Healthcare  Canada        7905343
4          5  Infosys      Retail      UK       15392192

##### Names of all tables

In [151]:
print(list(data_dict.keys()))

['Clients', 'Company_Financials', 'Employees', 'Office_Locations', 'Projects', 'Technologies']

##### # **Type A — Load & explore**

##### 1. Load `clients.csv` and display the first 5 rows and the shape.

In [152]:
data_dict['Clients'].head()

   Client_ID  Company    Industry Country  ContractValue
0          1    Wipro      Retail   India       39728043
1          2      TCS  Healthcare   India       41065784
2          3    Wipro  Healthcare   India       32180187
3          4      TCS  Healthcare  Canada        7905343
4          5  Infosys      Retail      UK       15392192

##### 2. Load `employees.csv` and check data types with `.info()`.

In [153]:
data_dict['Employees'].info()

<class 'pandas.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 7 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Employee_ID  250000 non-null  int64
 1   Company      250000 non-null  str
 2   Department   250000 non-null  str
 3   Role         250000 non-null  str
 4   Age          250000 non-null  int64
 5   Salary       250000 non-null  int64
 6   JoinDate     250000 non-null  str
dtypes: int64(3), str(4)
memory usage: 13.4 MB

In [154]:
print(list(data_dict.keys()))

['Clients', 'Company_Financials', 'Employees', 'Office_Locations', 'Projects', 'Technologies']

##### 3. Load `projects.csv` and check for missing values per column.

In [155]:
data_dict['Projects'].isnull().sum()

Project_ID     0
Company        0
Client_ID      0
Employee_ID    0
Technology     0
Budget         0
Status         0
dtype: int64

In [156]:
print(list(data_dict.keys()))

['Clients', 'Company_Financials', 'Employees', 'Office_Locations', 'Projects', 'Technologies']

##### 4. Load `offices.csv` and list all column names.

In [157]:
data_dict['Office_Locations'].columns

print('Column names for the table Office_Locations are :', data_dict['Office_Locations'].columns)

Column names for the table Office_Locations are : Index(['Office_ID', 'Company', 'Country', 'State', 'City', 'Employees'], dtype='str')

##### 5. Load `technologies.csv` and check for duplicate rows with `.duplicated()`.

In [158]:
data_dict['Technologies'].duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
149995    False
149996    False
149997    False
149998    False
149999    False
Length: 150000, dtype: bool

##### **Type B — Column selection**

##### 6. From `clients`, select just `Company` and `Industry`.

In [159]:
data_dict['Clients'][['Company','Industry']]

        Company    Industry
0         Wipro      Retail
1           TCS  Healthcare
2         Wipro  Healthcare
3           TCS  Healthcare
4       Infosys      Retail
...         ...         ...
119995  HCLTech  Healthcare
119996      TCS     Telecom
119997    Wipro     Banking
119998  Infosys  Healthcare
119999  Infosys     Telecom

[120000 rows x 2 columns]

In [160]:
print(list(data_dict.keys()))

['Clients', 'Company_Financials', 'Employees', 'Office_Locations', 'Projects', 'Technologies']

##### 7. From `employees`, select `Employee_ID`, `Role`, and `Salary`.

In [161]:
data_dict['Employees'][['Employee_ID','Role','Salary']]

        Employee_ID    Role  Salary
0                 1      QA   91806
1                 2      SE   14827
2                 3      BA  121727
3                 4     SSE   88985
4                 5      SE   35904
...             ...     ...     ...
249995       249996  DevOps   29369
249996       249997      QA   65865
249997       249998      QA   48007
249998       249999      SE   65756
249999       250000      QA  113592

[250000 rows x 3 columns]

In [162]:
print(list(data_dict.keys()))

['Clients', 'Company_Financials', 'Employees', 'Office_Locations', 'Projects', 'Technologies']

##### 8. From `projects`, select `Project_ID`, `Technology`, and `Status`.

In [163]:
data_dict['Projects'][['Project_ID','Technology','Status']]

        Project_ID Technology       Status
0                1      Azure  In Progress
1                2      Azure      On Hold
2                3        AWS      On Hold
3                4       Java      On Hold
4                5        GCP  In Progress
...            ...        ...          ...
179995      179996       Java    Completed
179996      179997        GCP    Completed
179997      179998        AWS    Completed
179998      179999        GCP  In Progress
179999      180000     Python  In Progress

[180000 rows x 3 columns]

##### 10. From `financials`, select `Company`, `Year`, and `Revenue`.

In [164]:
data_dict['Company_Financials'][['Company', 'Year', 'Revenue']]

        Company  Year  Revenue
0           TCS  2015     4812
1           TCS  2025     7712
2           TCS  2018     1234
3       HCLTech  2018     5357
4       Infosys  2026     6374
...         ...   ...      ...
119995  Infosys  2017     8410
119996      TCS  2015     5936
119997  Infosys  2016     3715
119998  HCLTech  2025     1416
119999  HCLTech  2022     3698

[120000 rows x 3 columns]

##### **Type C — Filtering rows**

##### 11. Filter `clients` to only rows where `Industry == 'Retail'`.

In [165]:
print(list(data_dict.keys()))

['Clients', 'Company_Financials', 'Employees', 'Office_Locations', 'Projects', 'Technologies']

In [166]:
data_dict['Clients'].loc[data_dict['Clients']['Industry'] == 'Retail'].head()

    Client_ID  Company Industry Country  ContractValue
0           1    Wipro   Retail   India       39728043
4           5  Infosys   Retail      UK       15392192
6           7    Wipro   Retail      UK       39845758
13         14  Infosys   Retail  Canada       26940688
16         17    Wipro   Retail      UK       13172681

##### 12. Filter `employees` to only rows where `Department == 'AI'`.

In [167]:
print(list(data_dict.keys()))

['Clients', 'Company_Financials', 'Employees', 'Office_Locations', 'Projects', 'Technologies']

In [168]:
data_dict['Employees'].loc[data_dict['Employees']['Department'] == 'AI'].head()

    Employee_ID  Company Department    Role  Age  Salary    JoinDate
0             1    Wipro         AI      QA   50   91806  11-04-2020
9            10  Infosys         AI      QA   49   27540  20-04-2020
18           19  Infosys         AI  DevOps   57  104793  29-04-2020
22           23  HCLTech         AI     SSE   33   57850  03-05-2020
24           25      TCS         AI      PM   35   92132  05-05-2020

##### 13. Filter `projects` to only rows where `Status == 'In Progress'`.

In [169]:
print(list(data_dict.keys()))

['Clients', 'Company_Financials', 'Employees', 'Office_Locations', 'Projects', 'Technologies']

In [170]:
data_dict['Projects'].loc[data_dict['Projects']['Status'] == 'In Progress'].head()

,Project_ID,Company,Client_ID,Employee_ID,Technology,Budget,Status
0,1,Wipro,32252,195820,Azure,8646817,In Progress
4,5,TCS,114709,100718,GCP,4313680,In Progress
6,7,HCLTech,113542,186129,Java,5171519,In Progress
7,8,TCS,72965,39418,Java,6434833,In Progress
9,10,HCLTech,59848,86628,SAP,133948,In Progress

##### 14. Filter `offices` to only rows where `Country == 'India'`.

In [171]:
print(list(data_dict.keys()))

['Clients', 'Company_Financials', 'Employees', 'Office_Locations', 'Projects', 'Technologies']

In [172]:
data_dict['Office_Locations'].head()

   Office_ID  Company Country State       City  Employees
0          1    Wipro  Canada    KA       Pune      10757
1          2  HCLTech   India    TS       Pune       7143
2          3    Wipro      UK    TS    Chennai       8807
3          4  HCLTech  Canada    WB    Chennai       3058
4          5    Wipro  Canada    TN  Bengaluru       8998

In [173]:
data_dict['Office_Locations'].loc[data_dict['Office_Locations']['Country'] == 'India'].head()

    Office_ID  Company Country State     City  Employees
1           2  HCLTech   India    TS     Pune       7143
5           6      TCS   India    TN  Kolkata       8237
7           8    Wipro   India    WB     Pune      13110
11         12  Infosys   India    TS     Pune       5469
16         17    Wipro   India    KA  Kolkata      12903

##### 15. Filter `financials` to only rows where `Year == 2021`.

In [174]:
print(list(data_dict.keys()))

['Clients', 'Company_Financials', 'Employees', 'Office_Locations', 'Projects', 'Technologies']

In [175]:
data_dict['Company_Financials'].head()

   Financial_ID  Company  Year Quarter  Revenue  Profit  Employees
0             1      TCS  2015      Q3     4812     994      86579
1             2      TCS  2025      Q1     7712     210      57811
2             3      TCS  2018      Q2     1234    2378     102124
3             4  HCLTech  2018      Q4     5357     106     248916
4             5  Infosys  2026      Q4     6374    1218      90758

In [176]:
data_dict['Company_Financials'].loc[data_dict['Company_Financials']['Year'] == 2021 ].head()

    Financial_ID  Company  Year Quarter  Revenue  Profit  Employees
7              8      TCS  2021      Q1     5603    1561     201349
14            15    Wipro  2021      Q3     1884     944     198682
42            43      TCS  2021      Q3     8254    1248     160888
60            61  Infosys  2021      Q2     1485    1342     145591
70            71    Wipro  2021      Q1     7111    2441      99828

##### **Type D — `.value_counts()`**

##### 16. Count how many clients fall into each `Industry`.

In [177]:
print(list(data_dict.keys()))

['Clients', 'Company_Financials', 'Employees', 'Office_Locations', 'Projects', 'Technologies']

In [178]:
data_dict['Clients'].head()

   Client_ID  Company    Industry Country  ContractValue
0          1    Wipro      Retail   India       39728043
1          2      TCS  Healthcare   India       41065784
2          3    Wipro  Healthcare   India       32180187
3          4      TCS  Healthcare  Canada        7905343
4          5  Infosys      Retail      UK       15392192

In [179]:
data_dict['Clients']['Industry'].value_counts()

Industry
Healthcare       24115
Manufacturing    24041
Retail           24018
Banking          23965
Telecom          23861
Name: count, dtype: int64

##### 17. Count how many employees fall into each `Department`.

In [180]:
print(list(data_dict.keys()))

['Clients', 'Company_Financials', 'Employees', 'Office_Locations', 'Projects', 'Technologies']

In [181]:
data_dict['Employees'].head()

   Employee_ID  Company   Department Role  Age  Salary    JoinDate
0            1    Wipro           AI   QA   50   91806  11-04-2020
1            2    Wipro      Finance   SE   21   14827  12-04-2020
2            3    Wipro      Finance   BA   49  121727  13-04-2020
3            4    Wipro  Engineering  SSE   43   88985  14-04-2020
4            5  Infosys      Finance   SE   25   35904  15-04-2020

In [182]:
data_dict['Employees']['Department'].value_counts()

Department
Support        31545
Finance        31396
AI             31325
Engineering    31222
HR             31214
Sales          31211
Cloud          31157
IT             30930
Name: count, dtype: int64

##### 18. Count how many projects fall into each `Status`.

In [183]:
data_dict['Projects'].head()

,Project_ID,Company,Client_ID,Employee_ID,Technology,Budget,Status
0,1,Wipro,32252,195820,Azure,8646817,In Progress
1,2,Wipro,21042,69871,Azure,6633547,On Hold
2,3,HCLTech,89295,148126,AWS,5647221,On Hold
3,4,Infosys,54119,115503,Java,7970162,On Hold
4,5,TCS,114709,100718,GCP,4313680,In Progress

In [184]:
data_dict['Projects']['Status'].value_counts()

Status
Completed      60121
On Hold        60032
In Progress    59847
Name: count, dtype: int64

##### 19. Count how many offices exist per `Company`.

In [185]:
data_dict['Office_Locations'].head()

   Office_ID  Company Country State       City  Employees
0          1    Wipro  Canada    KA       Pune      10757
1          2  HCLTech   India    TS       Pune       7143
2          3    Wipro      UK    TS    Chennai       8807
3          4  HCLTech  Canada    WB    Chennai       3058
4          5    Wipro  Canada    TN  Bengaluru       8998

In [186]:
data_dict['Office_Locations']['Company'].value_counts()

Company
Infosys    25163
TCS        25010
HCLTech    24963
Wipro      24864
Name: count, dtype: int64

##### 20. Count how many technologies fall into each `Technology` name.

In [187]:
data_dict['Technologies'].head()

   Technology_ID  Company Technology  Project_ID  Popularity
0              1  HCLTech        SAP      153468       57.75
1              2    Wipro        SAP       48952       57.73
2              3  HCLTech      Azure      146403       78.35
3              4      TCS     Python       39073       75.26
4              5      TCS      Azure       50553       85.76

In [188]:
data_dict['Technologies']['Technology'].value_counts()

Technology
AWS       25132
Java      25092
Python    25029
Azure     24962
SAP       24923
GCP       24862
Name: count, dtype: int64

##### **Type A — Single aggregate**

##### 1. Calculate the average `Salary` in `employees`.

In [189]:
data_dict['Employees'].head()

   Employee_ID  Company   Department Role  Age  Salary    JoinDate
0            1    Wipro           AI   QA   50   91806  11-04-2020
1            2    Wipro      Finance   SE   21   14827  12-04-2020
2            3    Wipro      Finance   BA   49  121727  13-04-2020
3            4    Wipro  Engineering  SSE   43   88985  14-04-2020
4            5  Infosys      Finance   SE   25   35904  15-04-2020

In [190]:
data_dict['Employees']['Salary'].mean()

print(f'Average salary of employees is: {data_dict['Employees']['Salary'].mean():.2f}')

Average salary of employees is: 78895.84

##### 2. Calculate the total `ContractValue` in `clients`.

In [191]:
data_dict['Clients'].head()

   Client_ID  Company    Industry Country  ContractValue
0          1    Wipro      Retail   India       39728043
1          2      TCS  Healthcare   India       41065784
2          3    Wipro  Healthcare   India       32180187
3          4      TCS  Healthcare  Canada        7905343
4          5  Infosys      Retail      UK       15392192

In [192]:
data_dict['Clients']['ContractValue'].sum()

print(f'The total contract value in clients is :{data_dict['Clients']['ContractValue'].sum():.2f}')

The total contract value in clients is :2999443706423.00

##### 3. Find the maximum `Budget` in `projects`.

In [193]:
data_dict['Projects'].head()

,Project_ID,Company,Client_ID,Employee_ID,Technology,Budget,Status
0,1,Wipro,32252,195820,Azure,8646817,In Progress
1,2,Wipro,21042,69871,Azure,6633547,On Hold
2,3,HCLTech,89295,148126,AWS,5647221,On Hold
3,4,Infosys,54119,115503,Java,7970162,On Hold
4,5,TCS,114709,100718,GCP,4313680,In Progress

In [194]:
data_dict['Projects']['Budget'].max()

print(f'Maximum Budget in projects is: {data_dict['Projects']['Budget'].max():.2f}')

Maximum Budget in projects is: 9999902.00

##### 4. Find the minimum `Profit` in `financials`.

In [195]:
data_dict['Company_Financials'].head()

   Financial_ID  Company  Year Quarter  Revenue  Profit  Employees
0             1      TCS  2015      Q3     4812     994      86579
1             2      TCS  2025      Q1     7712     210      57811
2             3      TCS  2018      Q2     1234    2378     102124
3             4  HCLTech  2018      Q4     5357     106     248916
4             5  Infosys  2026      Q4     6374    1218      90758

In [196]:
data_dict['Company_Financials']['Profit'].min()

print(f'The minimum profit in finance is : {data_dict['Company_Financials']['Profit'].min():.2f}')

The minimum profit in finance is : 80.00

##### 5. Count the total number of rows in `offices`.

In [197]:
data_dict['Office_Locations'].head()

   Office_ID  Company Country State       City  Employees
0          1    Wipro  Canada    KA       Pune      10757
1          2  HCLTech   India    TS       Pune       7143
2          3    Wipro      UK    TS    Chennai       8807
3          4  HCLTech  Canada    WB    Chennai       3058
4          5    Wipro  Canada    TN  Bengaluru       8998

In [198]:
len(data_dict['Office_Locations'])

print(f'Total number of rows in office table are : {len(data_dict['Office_Locations'])}')

Total number of rows in office table are : 100000

##### **Type B — `.groupby()` + `.count()` / `.size()`**

##### 6. Group `employees` by `Department` and count employees in each.

In [199]:
data_dict['Employees'].head()

   Employee_ID  Company   Department Role  Age  Salary    JoinDate
0            1    Wipro           AI   QA   50   91806  11-04-2020
1            2    Wipro      Finance   SE   21   14827  12-04-2020
2            3    Wipro      Finance   BA   49  121727  13-04-2020
3            4    Wipro  Engineering  SSE   43   88985  14-04-2020
4            5  Infosys      Finance   SE   25   35904  15-04-2020

In [200]:
data_dict['Employees'].groupby('Department').size()

Department
AI             31325
Cloud          31157
Engineering    31222
Finance        31396
HR             31214
IT             30930
Sales          31211
Support        31545
dtype: int64

##### 7. Group `clients` by `Industry` and count clients in each.

In [201]:
data_dict['Clients'].head()

   Client_ID  Company    Industry Country  ContractValue
0          1    Wipro      Retail   India       39728043
1          2      TCS  Healthcare   India       41065784
2          3    Wipro  Healthcare   India       32180187
3          4      TCS  Healthcare  Canada        7905343
4          5  Infosys      Retail      UK       15392192

In [202]:
data_dict['Clients'].groupby('Industry').size()

Industry
Banking          23965
Healthcare       24115
Manufacturing    24041
Retail           24018
Telecom          23861
dtype: int64

##### 8. Group `projects` by `Status` and count projects in each.

In [203]:
data_dict['Projects'].head()

,Project_ID,Company,Client_ID,Employee_ID,Technology,Budget,Status
0,1,Wipro,32252,195820,Azure,8646817,In Progress
1,2,Wipro,21042,69871,Azure,6633547,On Hold
2,3,HCLTech,89295,148126,AWS,5647221,On Hold
3,4,Infosys,54119,115503,Java,7970162,On Hold
4,5,TCS,114709,100718,GCP,4313680,In Progress

In [204]:
data_dict['Projects'].groupby('Status').size()

Status
Completed      60121
In Progress    59847
On Hold        60032
dtype: int64

##### 9. Group `offices` by `Country` and count offices in each.

In [205]:
data_dict['Office_Locations'].head()

   Office_ID  Company Country State       City  Employees
0          1    Wipro  Canada    KA       Pune      10757
1          2  HCLTech   India    TS       Pune       7143
2          3    Wipro      UK    TS    Chennai       8807
3          4  HCLTech  Canada    WB    Chennai       3058
4          5    Wipro  Canada    TN  Bengaluru       8998

In [206]:
data_dict['Office_Locations'].groupby('Country').size()

Country
Canada     19919
Germany    19994
India      20019
UK         20068
USA        20000
dtype: int64

##### 10. Group `financials` by `Company` and count records in each.

In [207]:
data_dict['Company_Financials'].head()

   Financial_ID  Company  Year Quarter  Revenue  Profit  Employees
0             1      TCS  2015      Q3     4812     994      86579
1             2      TCS  2025      Q1     7712     210      57811
2             3      TCS  2018      Q2     1234    2378     102124
3             4  HCLTech  2018      Q4     5357     106     248916
4             5  Infosys  2026      Q4     6374    1218      90758

In [208]:
data_dict['Company_Financials'].groupby('Company').size()

Company
HCLTech    29753
Infosys    29963
TCS        30186
Wipro      30098
dtype: int64

##### **Type C — `.groupby()` + `.mean()` / `.sum()`**

##### 11. Group `employees` by `Department` and find average `Salary`.

In [209]:
data_dict['Employees'].head()

   Employee_ID  Company   Department Role  Age  Salary    JoinDate
0            1    Wipro           AI   QA   50   91806  11-04-2020
1            2    Wipro      Finance   SE   21   14827  12-04-2020
2            3    Wipro      Finance   BA   49  121727  13-04-2020
3            4    Wipro  Engineering  SSE   43   88985  14-04-2020
4            5  Infosys      Finance   SE   25   35904  15-04-2020

In [210]:
data_dict['Employees'].groupby('Department')['Salary'].mean().round(2)

Department
AI             79439.99
Cloud          78825.29
Engineering    78711.19
Finance        78867.22
HR             78975.95
IT             78833.82
Sales          78837.07
Support        78676.08
Name: Salary, dtype: float64

##### 12. Group `clients` by `Industry` and find total `ContractValue`.

In [211]:
data_dict['Clients'].head()

   Client_ID  Company    Industry Country  ContractValue
0          1    Wipro      Retail   India       39728043
1          2      TCS  Healthcare   India       41065784
2          3    Wipro  Healthcare   India       32180187
3          4      TCS  Healthcare  Canada        7905343
4          5  Infosys      Retail      UK       15392192

In [212]:
data_dict['Clients'].groupby('Industry')['ContractValue'].mean()

Industry
Banking          2.499614e+07
Healthcare       2.489478e+07
Manufacturing    2.509016e+07
Retail           2.495520e+07
Telecom          2.504116e+07
Name: ContractValue, dtype: float64

##### 13. Group `projects` by `Technology` and find average `Budget`.

In [213]:
print(list(data_dict.keys()))

['Clients', 'Company_Financials', 'Employees', 'Office_Locations', 'Projects', 'Technologies']

In [214]:
data_dict['Projects'].head()

,Project_ID,Company,Client_ID,Employee_ID,Technology,Budget,Status
0,1,Wipro,32252,195820,Azure,8646817,In Progress
1,2,Wipro,21042,69871,Azure,6633547,On Hold
2,3,HCLTech,89295,148126,AWS,5647221,On Hold
3,4,Infosys,54119,115503,Java,7970162,On Hold
4,5,TCS,114709,100718,GCP,4313680,In Progress

In [215]:
data_dict['Projects'].groupby('Technology').size()

Technology
AWS       29989
Azure     30103
GCP       30033
Java      29899
Python    30038
SAP       29938
dtype: int64

In [216]:
data_dict['Projects'].groupby('Technology')['Budget'].mean()

Technology
AWS       5.031285e+06
Azure     5.003498e+06
GCP       5.021909e+06
Java      5.028624e+06
Python    5.034717e+06
SAP       5.038316e+06
Name: Budget, dtype: float64

##### 14. Group `financials` by `Company` and find total `Revenue`.

In [217]:
data_dict['Company_Financials'].head()

   Financial_ID  Company  Year Quarter  Revenue  Profit  Employees
0             1      TCS  2015      Q3     4812     994      86579
1             2      TCS  2025      Q1     7712     210      57811
2             3      TCS  2018      Q2     1234    2378     102124
3             4  HCLTech  2018      Q4     5357     106     248916
4             5  Infosys  2026      Q4     6374    1218      90758

In [218]:
data_dict['Company_Financials'].groupby('Company').size()

Company
HCLTech    29753
Infosys    29963
TCS        30186
Wipro      30098
dtype: int64

In [219]:
data_dict['Company_Financials'].groupby('Company')['Revenue'].mean()

Company
HCLTech    4905.237959
Infosys    4910.797650
TCS        4908.652885
Wipro      4880.339059
Name: Revenue, dtype: float64

##### 15. Group `technologies` by `Technology` and find average `Popularity`.

In [220]:
### Python

# ['Clients', 'Company_Financials', 'Employees', 'Office_Locations', 'Projects', 'Technologies']




# **Type D — `.groupby()` + `.agg()` (multiple stats at once)**
# 16. Group `employees` by `Department` and get both mean and max `Salary` in one `.agg()`.
# 17. Group `clients` by `Industry` and get both sum and count of `ContractValue`.
# 18. Group `projects` by `Status` and get min, max, and mean `Budget`.
# 19. Group `financials` by `Company` and get sum of `Revenue` and sum of `Profit`.
# 20. Group `offices` by `Company` and get count of offices and sum of `Employees`.

In [221]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus
import os, glob
import pandas as pd

# --- 1. Connection (set up once) ---
server = r"LAPTOP-A70F1ENF\SHIVASQLEXPRESS"
database = "P_Big4_India"
driver = "ODBC Driver 17 for SQL Server"

params = quote_plus(
    f"DRIVER={{{driver}}};"
    f"SERVER={server};"
    f"DATABASE={database};"
    f"Trusted_Connection=yes;"
)
engine = create_engine(f"mssql+pyodbc:///?odbc_connect={params}")

# --- 2. Load all CSVs into a dict ---
folder_path = r"C:\Users\Shiva Thakur\OneDrive\Desktop\Github\Practice\Daily Python\E_Big4_India"
data_dict = {
    os.path.splitext(os.path.basename(f))[0]: pd.read_csv(f)
    for f in glob.glob(os.path.join(folder_path, "*.csv"))
}

# --- 3. Push each DataFrame to its own table ---
for table_name, df in data_dict.items():
    df.to_sql(table_name, engine, if_exists="replace", index=False)
    print(f"Loaded table: {table_name} ({df.shape[0]} rows)")

# --- 4. Sanity check ---
for table_name in data_dict.keys():
    print(f"\n--- {table_name} ---")
    print(pd.read_sql(f"SELECT TOP 5 * FROM [{table_name}];", engine))