In [225]:
import ast
import pandas as pd
import numpy as nb
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

##### **Loading & Exploring**

##### 1. Load the CSV into a DataFrame and display the first 5 rows.

In [226]:
df = pd.read_csv('Data_CO2_emission.csv')

In [227]:
df.head(5)

,Country Name,country_code,Region,Indicator Name,1990,1991,1992,1993,1994,1995,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2019.1
0,Aruba,ABW,Latin America & Caribbean,CO2 emissions (metric tons per capita),NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,South Asia,CO2 emissions (metric tons per capita),0.191745,0.167682,0.095958,0.084721,0.075546,0.068468,...,0.296506,0.259295,0.185624,0.146236,0.172897,0.149789,0.131695,0.163295,0.159824,0.159824
2,Angola,AGO,Sub-Saharan Africa,CO2 emissions (metric tons per capita),0.553662,0.544539,0.543557,0.708984,0.836804,0.912141,...,0.985522,0.950696,1.036294,1.099779,1.135044,1.031811,0.813301,0.777675,0.792137,0.792137
3,Albania,ALB,Europe & Central Asia,CO2 emissions (metric tons per capita),1.819542,1.242810,0.683700,0.638307,0.645355,0.605436,...,1.669423,1.503240,1.533630,1.668337,1.603775,1.557664,1.788786,1.782739,1.692248,1.692248
4,Andorra,AND,Europe & Central Asia,CO2 emissions (metric tons per capita),7.521832,7.235379,6.963079,6.724178,6.541579,6.733479,...,5.850886,5.944654,5.942800,5.807128,6.026182,6.080600,6.104134,6.362975,6.481217,6.481217

##### 2. Check the shape of the DataFrame (rows, columns).

In [228]:
print('Size of dataset is :', df.size)
print('Shape of dataset is :', df.shape)

Size of dataset is : 7525
Shape of dataset is : (215, 35)

##### 3. List all column names.

In [229]:
print('Names of columns are :', df.columns.tolist())

Names of columns are : ['Country Name', 'country_code', 'Region', 'Indicator Name', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2019.1']

##### 4. Check the data types of each column using `.info()`.

In [230]:
df.dtypes

Country Name          str
country_code          str
Region                str
Indicator Name        str
1990              float64
1991              float64
1992              float64
1993              float64
1994              float64
1995              float64
1996              float64
1997              float64
1998              float64
1999              float64
2000              float64
2001              float64
2002              float64
2003              float64
2004              float64
2005              float64
2006              float64
2007              float64
2008              float64
2009              float64
2010              float64
2011              float64
2012              float64
2013              float64
2014              float64
2015              float64
2016              float64
2017              float64
2018              float64
2019              float64
2019.1            float64
dtype: object

In [231]:
df.describe()

,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2019.1
count,185.000000,186.000000,189.000000,189.000000,189.000000,190.000000,190.000000,190.000000,189.000000,189.000000,...,191.000000,191.000000,191.000000,191.000000,191.000000,191.000000,191.000000,191.000000,191.000000,191.000000
mean,4.404504,4.290648,4.174834,4.085472,4.045067,4.136628,4.211147,4.250716,4.282809,4.265652,...,4.392175,4.440399,4.326678,4.226973,4.184129,4.195432,4.199802,4.164970,4.115138,4.115138
std,5.577460,5.577411,5.362451,5.385712,5.464233,5.510400,5.656146,5.857395,5.846361,5.917358,...,5.284152,5.277192,5.203024,5.079421,4.985068,4.938351,4.869959,4.748086,4.714595,4.714595
min,0.001183,0.001158,0.001130,0.001100,0.001071,0.001043,0.000000,0.000991,0.035567,0.036699,...,0.040186,0.040017,0.026979,0.029121,0.039370,0.030715,0.035013,0.037113,0.036986,0.036986
25%,0.434249,0.452759,0.471380,0.448535,0.406659,0.423225,0.461902,0.475029,0.496752,0.509021,...,0.630991,0.633505,0.675626,0.669278,0.667341,0.728493,0.791952,0.795606,0.801764,0.801764
50%,1.914543,1.941825,2.012212,1.867589,1.830972,1.832534,1.875031,2.034502,2.156377,2.132253,...,2.492730,2.562000,2.542694,2.620389,2.579300,2.597787,2.609976,2.584477,2.717624,2.717624
75%,6.910335,6.497471,6.482311,6.430944,6.337175,6.360589,6.581746,6.478028,6.369907,6.233211,...,6.269888,6.336345,6.069882,5.814026,5.776685,5.802129,5.834060,5.770189,5.585162,5.585162
max,30.195189,31.778496,29.632441,33.122025,36.466263,37.102174,40.074177,47.429575,48.045021,50.833850,...,33.494413,34.188222,32.598940,33.205895,33.043510,32.745888,32.127990,31.067533,32.474469,32.474469

##### 5. Check how many missing (null) values exist in each column.

In [232]:
df.isnull().sum()

Country Name       0
country_code       0
Region             0
Indicator Name     0
1990              30
1991              29
1992              26
1993              26
1994              26
1995              25
1996              25
1997              25
1998              26
1999              26
2000              25
2001              25
2002              24
2003              24
2004              24
2005              24
2006              24
2007              24
2008              24
2009              24
2010              24
2011              24
2012              24
2013              24
2014              24
2015              24
2016              24
2017              24
2018              24
2019              24
2019.1            24
dtype: int64

##### **Basic Filtering & Selection**

##### 6. Select just the `Country Name` and `Region` columns.

In [233]:
df.head()

,Country Name,country_code,Region,Indicator Name,1990,1991,1992,1993,1994,1995,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2019.1
0,Aruba,ABW,Latin America & Caribbean,CO2 emissions (metric tons per capita),NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,South Asia,CO2 emissions (metric tons per capita),0.191745,0.167682,0.095958,0.084721,0.075546,0.068468,...,0.296506,0.259295,0.185624,0.146236,0.172897,0.149789,0.131695,0.163295,0.159824,0.159824
2,Angola,AGO,Sub-Saharan Africa,CO2 emissions (metric tons per capita),0.553662,0.544539,0.543557,0.708984,0.836804,0.912141,...,0.985522,0.950696,1.036294,1.099779,1.135044,1.031811,0.813301,0.777675,0.792137,0.792137
3,Albania,ALB,Europe & Central Asia,CO2 emissions (metric tons per capita),1.819542,1.242810,0.683700,0.638307,0.645355,0.605436,...,1.669423,1.503240,1.533630,1.668337,1.603775,1.557664,1.788786,1.782739,1.692248,1.692248
4,Andorra,AND,Europe & Central Asia,CO2 emissions (metric tons per capita),7.521832,7.235379,6.963079,6.724178,6.541579,6.733479,...,5.850886,5.944654,5.942800,5.807128,6.026182,6.080600,6.104134,6.362975,6.481217,6.481217

In [234]:
df[['Country Name','Region']]

     Country Name                      Region
0           Aruba   Latin America & Caribbean
1     Afghanistan                  South Asia
2          Angola          Sub-Saharan Africa
3         Albania       Europe & Central Asia
4         Andorra       Europe & Central Asia
..            ...                         ...
210         Samoa         East Asia & Pacific
211   Yemen, Rep.  Middle East & North Africa
212  South Africa          Sub-Saharan Africa
213        Zambia          Sub-Saharan Africa
214      Zimbabwe          Sub-Saharan Africa

[215 rows x 2 columns]

##### 7. Filter the DataFrame to show only rows where `Region` == `'South Asia'`.

In [235]:
df.head()

,Country Name,country_code,Region,Indicator Name,1990,1991,1992,1993,1994,1995,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2019.1
0,Aruba,ABW,Latin America & Caribbean,CO2 emissions (metric tons per capita),NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,South Asia,CO2 emissions (metric tons per capita),0.191745,0.167682,0.095958,0.084721,0.075546,0.068468,...,0.296506,0.259295,0.185624,0.146236,0.172897,0.149789,0.131695,0.163295,0.159824,0.159824
2,Angola,AGO,Sub-Saharan Africa,CO2 emissions (metric tons per capita),0.553662,0.544539,0.543557,0.708984,0.836804,0.912141,...,0.985522,0.950696,1.036294,1.099779,1.135044,1.031811,0.813301,0.777675,0.792137,0.792137
3,Albania,ALB,Europe & Central Asia,CO2 emissions (metric tons per capita),1.819542,1.242810,0.683700,0.638307,0.645355,0.605436,...,1.669423,1.503240,1.533630,1.668337,1.603775,1.557664,1.788786,1.782739,1.692248,1.692248
4,Andorra,AND,Europe & Central Asia,CO2 emissions (metric tons per capita),7.521832,7.235379,6.963079,6.724178,6.541579,6.733479,...,5.850886,5.944654,5.942800,5.807128,6.026182,6.080600,6.104134,6.362975,6.481217,6.481217

In [236]:
df[df['Region'] == 'South Asia']

,Country Name,country_code,Region,Indicator Name,1990,1991,1992,1993,1994,1995,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2019.1
1,Afghanistan,AFG,South Asia,CO2 emissions (metric tons per capita),0.191745,0.167682,0.095958,0.084721,0.075546,0.068468,...,0.296506,0.259295,0.185624,0.146236,0.172897,0.149789,0.131695,0.163295,0.159824,0.159824
17,Bangladesh,BGD,South Asia,CO2 emissions (metric tons per capita),0.111658,0.102558,0.109461,0.113910,0.120102,0.143701,...,0.364567,0.384025,0.396697,0.413093,0.461997,0.470828,0.496852,0.517113,0.556529,0.556529
29,Bhutan,BTN,South Asia,CO2 emissions (metric tons per capita),0.150716,0.243156,0.224498,0.244090,0.263205,0.299273,...,0.851006,0.912224,0.943350,0.973503,1.057859,1.262376,1.301030,1.391842,1.375977,1.375977
88,India,IND,South Asia,CO2 emissions (metric tons per capita),0.645362,0.681306,0.688755,0.702337,0.725358,0.765476,...,1.405068,1.508508,1.539948,1.657231,1.647152,1.657396,1.733361,1.812696,1.797620,1.797620
112,Sri Lanka,LKA,South Asia,CO2 emissions (metric tons per capita),0.221635,0.227535,0.295994,0.283964,0.318882,0.319028,...,0.755938,0.824969,0.703425,0.847050,0.970911,1.034288,1.089349,1.000923,1.090676,1.090676
123,Maldives,MDV,South Asia,CO2 emissions (metric tons per capita),0.716978,0.696430,0.973458,0.824416,0.804563,1.023042,...,2.654451,2.869867,2.719013,3.149295,3.011558,3.701328,3.746993,4.072103,3.973956,3.973956
145,Nepal,NPL,South Asia,CO2 emissions (metric tons per capita),0.049721,0.060807,0.061690,0.068814,0.082696,0.088061,...,0.192299,0.222311,0.226253,0.264997,0.266148,0.381830,0.451639,0.540652,0.470136,0.470136
149,Pakistan,PAK,South Asia,CO2 emissions (metric tons per capita),0.548362,0.544419,0.588002,0.629875,0.633502,0.668461,...,0.772880,0.767887,0.763669,0.789739,0.823008,0.889401,0.956345,0.882587,0.879965,0.879965

##### 8. Find all rows for `'India'`.

In [237]:
df.head()

,Country Name,country_code,Region,Indicator Name,1990,1991,1992,1993,1994,1995,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2019.1
0,Aruba,ABW,Latin America & Caribbean,CO2 emissions (metric tons per capita),NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,South Asia,CO2 emissions (metric tons per capita),0.191745,0.167682,0.095958,0.084721,0.075546,0.068468,...,0.296506,0.259295,0.185624,0.146236,0.172897,0.149789,0.131695,0.163295,0.159824,0.159824
2,Angola,AGO,Sub-Saharan Africa,CO2 emissions (metric tons per capita),0.553662,0.544539,0.543557,0.708984,0.836804,0.912141,...,0.985522,0.950696,1.036294,1.099779,1.135044,1.031811,0.813301,0.777675,0.792137,0.792137
3,Albania,ALB,Europe & Central Asia,CO2 emissions (metric tons per capita),1.819542,1.242810,0.683700,0.638307,0.645355,0.605436,...,1.669423,1.503240,1.533630,1.668337,1.603775,1.557664,1.788786,1.782739,1.692248,1.692248
4,Andorra,AND,Europe & Central Asia,CO2 emissions (metric tons per capita),7.521832,7.235379,6.963079,6.724178,6.541579,6.733479,...,5.850886,5.944654,5.942800,5.807128,6.026182,6.080600,6.104134,6.362975,6.481217,6.481217

In [238]:
df[df['Country Name'] == 'India']

,Country Name,country_code,Region,Indicator Name,1990,1991,1992,1993,1994,1995,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2019.1
88,India,IND,South Asia,CO2 emissions (metric tons per capita),0.645362,0.681306,0.688755,0.702337,0.725358,0.765476,...,1.405068,1.508508,1.539948,1.657231,1.647152,1.657396,1.733361,1.812696,1.79762,1.79762

##### 9. Drop the duplicate `2019` column (there are two — keep only one).

In [239]:
df.head()

,Country Name,country_code,Region,Indicator Name,1990,1991,1992,1993,1994,1995,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2019.1
0,Aruba,ABW,Latin America & Caribbean,CO2 emissions (metric tons per capita),NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,South Asia,CO2 emissions (metric tons per capita),0.191745,0.167682,0.095958,0.084721,0.075546,0.068468,...,0.296506,0.259295,0.185624,0.146236,0.172897,0.149789,0.131695,0.163295,0.159824,0.159824
2,Angola,AGO,Sub-Saharan Africa,CO2 emissions (metric tons per capita),0.553662,0.544539,0.543557,0.708984,0.836804,0.912141,...,0.985522,0.950696,1.036294,1.099779,1.135044,1.031811,0.813301,0.777675,0.792137,0.792137
3,Albania,ALB,Europe & Central Asia,CO2 emissions (metric tons per capita),1.819542,1.242810,0.683700,0.638307,0.645355,0.605436,...,1.669423,1.503240,1.533630,1.668337,1.603775,1.557664,1.788786,1.782739,1.692248,1.692248
4,Andorra,AND,Europe & Central Asia,CO2 emissions (metric tons per capita),7.521832,7.235379,6.963079,6.724178,6.541579,6.733479,...,5.850886,5.944654,5.942800,5.807128,6.026182,6.080600,6.104134,6.362975,6.481217,6.481217

In [240]:
col = ['2019.1']
df = df.drop(columns = col)

In [241]:
print(df.columns.to_list())

['Country Name', 'country_code', 'Region', 'Indicator Name', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019']

##### 10. Count how many unique countries are in the dataset.

In [242]:
df.head()

,Country Name,country_code,Region,Indicator Name,1990,1991,1992,1993,1994,1995,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Aruba,ABW,Latin America & Caribbean,CO2 emissions (metric tons per capita),NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,South Asia,CO2 emissions (metric tons per capita),0.191745,0.167682,0.095958,0.084721,0.075546,0.068468,...,0.243614,0.296506,0.259295,0.185624,0.146236,0.172897,0.149789,0.131695,0.163295,0.159824
2,Angola,AGO,Sub-Saharan Africa,CO2 emissions (metric tons per capita),0.553662,0.544539,0.543557,0.708984,0.836804,0.912141,...,0.976184,0.985522,0.950696,1.036294,1.099779,1.135044,1.031811,0.813301,0.777675,0.792137
3,Albania,ALB,Europe & Central Asia,CO2 emissions (metric tons per capita),1.819542,1.242810,0.683700,0.638307,0.645355,0.605436,...,1.527624,1.669423,1.503240,1.533630,1.668337,1.603775,1.557664,1.788786,1.782739,1.692248
4,Andorra,AND,Europe & Central Asia,CO2 emissions (metric tons per capita),7.521832,7.235379,6.963079,6.724178,6.541579,6.733479,...,6.157198,5.850886,5.944654,5.942800,5.807128,6.026182,6.080600,6.104134,6.362975,6.481217

In [243]:
#df.value_counts('Country Name')

print('Number of unique countries is :', df['Country Name'].nunique())
# df['Country Name'].nunique()

Number of unique countries is : 215

##### **Simple Calculations**

##### 11. Find the average CO2 emission value for the year `2019` across all countries.

In [244]:
df.head()

,Country Name,country_code,Region,Indicator Name,1990,1991,1992,1993,1994,1995,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Aruba,ABW,Latin America & Caribbean,CO2 emissions (metric tons per capita),NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,South Asia,CO2 emissions (metric tons per capita),0.191745,0.167682,0.095958,0.084721,0.075546,0.068468,...,0.243614,0.296506,0.259295,0.185624,0.146236,0.172897,0.149789,0.131695,0.163295,0.159824
2,Angola,AGO,Sub-Saharan Africa,CO2 emissions (metric tons per capita),0.553662,0.544539,0.543557,0.708984,0.836804,0.912141,...,0.976184,0.985522,0.950696,1.036294,1.099779,1.135044,1.031811,0.813301,0.777675,0.792137
3,Albania,ALB,Europe & Central Asia,CO2 emissions (metric tons per capita),1.819542,1.242810,0.683700,0.638307,0.645355,0.605436,...,1.527624,1.669423,1.503240,1.533630,1.668337,1.603775,1.557664,1.788786,1.782739,1.692248
4,Andorra,AND,Europe & Central Asia,CO2 emissions (metric tons per capita),7.521832,7.235379,6.963079,6.724178,6.541579,6.733479,...,6.157198,5.850886,5.944654,5.942800,5.807128,6.026182,6.080600,6.104134,6.362975,6.481217

In [245]:
avg_emission = df['2019'].mean()
print(f'Average CO2 emission for 2019 is : {avg_emission:.2f}')
# f prefix tells Python this is an f-string, which lets you embed variable values directly inside a string using curly braces {}
# .2f means "format as a fixed-point (decimal) number, rounded to 2 decimal places.

# {value:.0f} → rounds to a whole number, no decimals
# {value:,.2f} → adds comma separators for thousands (e.g. 1,234.56)
# {value:.2%} → formats a decimal as a percentage (e.g. 0.418 becomes 41.80%)

Average CO2 emission for 2019 is : 4.12

##### 12. Find which country had the highest CO2 emission in `2019`.

In [246]:
df.head()

,Country Name,country_code,Region,Indicator Name,1990,1991,1992,1993,1994,1995,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Aruba,ABW,Latin America & Caribbean,CO2 emissions (metric tons per capita),NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,South Asia,CO2 emissions (metric tons per capita),0.191745,0.167682,0.095958,0.084721,0.075546,0.068468,...,0.243614,0.296506,0.259295,0.185624,0.146236,0.172897,0.149789,0.131695,0.163295,0.159824
2,Angola,AGO,Sub-Saharan Africa,CO2 emissions (metric tons per capita),0.553662,0.544539,0.543557,0.708984,0.836804,0.912141,...,0.976184,0.985522,0.950696,1.036294,1.099779,1.135044,1.031811,0.813301,0.777675,0.792137
3,Albania,ALB,Europe & Central Asia,CO2 emissions (metric tons per capita),1.819542,1.242810,0.683700,0.638307,0.645355,0.605436,...,1.527624,1.669423,1.503240,1.533630,1.668337,1.603775,1.557664,1.788786,1.782739,1.692248
4,Andorra,AND,Europe & Central Asia,CO2 emissions (metric tons per capita),7.521832,7.235379,6.963079,6.724178,6.541579,6.733479,...,6.157198,5.850886,5.944654,5.942800,5.807128,6.026182,6.080600,6.104134,6.362975,6.481217

In [247]:
highest_country_2019 = df.loc[df['2019'].idxmax(), 'Country Name']
print(f'Country with highest CO2 emission in 2019 is {highest_country_2019}')

# df['2019'].idxmax() — finds the index label of the row with the maximum value in the 2019 column (not the value itself, but where it is).
# df.loc[..., 'Country'] — uses that index to look up the corresponding value in the Country column.

Country with highest CO2 emission in 2019 is Qatar

##### 13. Find which country had the lowest CO2 emission in `2019` (excluding missing values).

In [248]:
df.head()

,Country Name,country_code,Region,Indicator Name,1990,1991,1992,1993,1994,1995,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Aruba,ABW,Latin America & Caribbean,CO2 emissions (metric tons per capita),NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,South Asia,CO2 emissions (metric tons per capita),0.191745,0.167682,0.095958,0.084721,0.075546,0.068468,...,0.243614,0.296506,0.259295,0.185624,0.146236,0.172897,0.149789,0.131695,0.163295,0.159824
2,Angola,AGO,Sub-Saharan Africa,CO2 emissions (metric tons per capita),0.553662,0.544539,0.543557,0.708984,0.836804,0.912141,...,0.976184,0.985522,0.950696,1.036294,1.099779,1.135044,1.031811,0.813301,0.777675,0.792137
3,Albania,ALB,Europe & Central Asia,CO2 emissions (metric tons per capita),1.819542,1.242810,0.683700,0.638307,0.645355,0.605436,...,1.527624,1.669423,1.503240,1.533630,1.668337,1.603775,1.557664,1.788786,1.782739,1.692248
4,Andorra,AND,Europe & Central Asia,CO2 emissions (metric tons per capita),7.521832,7.235379,6.963079,6.724178,6.541579,6.733479,...,6.157198,5.850886,5.944654,5.942800,5.807128,6.026182,6.080600,6.104134,6.362975,6.481217

In [249]:
Lowest_CO2_2019 = df.loc[df['2019'].idxmin(), 'Country Name']
print(f'Lowest CO2 emission for a country was {Lowest_CO2_2019}')

#idxmin() (like idxmax(), mean(), min(), max(), etc.) automatically excludes NaN values by default in pandas.


# One edge case to be aware of: if the 2019 column is entirely NaN (no valid values at all),
# idxmin() will raise a ValueError since there's nothing to compare.
# If you want to be extra explicit about excluding missing values (e.g., for a teacher or portfolio reviewer to see the intent clearly),
# you could optionally write:

# valid_2019 = df.dropna(subset=['2019'])
# Lowest_CO2_2019 = valid_2019.loc[valid_2019['2019'].idxmin(), 'Country Name']
# print(f'Lowest CO2 emission for a country was {Lowest_CO2_2019}')

Lowest CO2 emission for a country was Congo, Dem. Rep.

##### 14. Count how many countries belong to each `Region` using `.value_counts()`.

In [250]:
df.head()

,Country Name,country_code,Region,Indicator Name,1990,1991,1992,1993,1994,1995,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Aruba,ABW,Latin America & Caribbean,CO2 emissions (metric tons per capita),NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,South Asia,CO2 emissions (metric tons per capita),0.191745,0.167682,0.095958,0.084721,0.075546,0.068468,...,0.243614,0.296506,0.259295,0.185624,0.146236,0.172897,0.149789,0.131695,0.163295,0.159824
2,Angola,AGO,Sub-Saharan Africa,CO2 emissions (metric tons per capita),0.553662,0.544539,0.543557,0.708984,0.836804,0.912141,...,0.976184,0.985522,0.950696,1.036294,1.099779,1.135044,1.031811,0.813301,0.777675,0.792137
3,Albania,ALB,Europe & Central Asia,CO2 emissions (metric tons per capita),1.819542,1.242810,0.683700,0.638307,0.645355,0.605436,...,1.527624,1.669423,1.503240,1.533630,1.668337,1.603775,1.557664,1.788786,1.782739,1.692248
4,Andorra,AND,Europe & Central Asia,CO2 emissions (metric tons per capita),7.521832,7.235379,6.963079,6.724178,6.541579,6.733479,...,6.157198,5.850886,5.944654,5.942800,5.807128,6.026182,6.080600,6.104134,6.362975,6.481217

In [251]:
df.value_counts('Region')

Region
Europe & Central Asia         56
Sub-Saharan Africa            48
Latin America & Caribbean     42
East Asia & Pacific           37
Middle East & North Africa    21
South Asia                     8
North America                  3
Name: count, dtype: int64

##### 15. Calculate the total (sum) of CO2 emissions for `2019` grouped by `Region`.

In [252]:
df.head()

,Country Name,country_code,Region,Indicator Name,1990,1991,1992,1993,1994,1995,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Aruba,ABW,Latin America & Caribbean,CO2 emissions (metric tons per capita),NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,South Asia,CO2 emissions (metric tons per capita),0.191745,0.167682,0.095958,0.084721,0.075546,0.068468,...,0.243614,0.296506,0.259295,0.185624,0.146236,0.172897,0.149789,0.131695,0.163295,0.159824
2,Angola,AGO,Sub-Saharan Africa,CO2 emissions (metric tons per capita),0.553662,0.544539,0.543557,0.708984,0.836804,0.912141,...,0.976184,0.985522,0.950696,1.036294,1.099779,1.135044,1.031811,0.813301,0.777675,0.792137
3,Albania,ALB,Europe & Central Asia,CO2 emissions (metric tons per capita),1.819542,1.242810,0.683700,0.638307,0.645355,0.605436,...,1.527624,1.669423,1.503240,1.533630,1.668337,1.603775,1.557664,1.788786,1.782739,1.692248
4,Andorra,AND,Europe & Central Asia,CO2 emissions (metric tons per capita),7.521832,7.235379,6.963079,6.724178,6.541579,6.733479,...,6.157198,5.850886,5.944654,5.942800,5.807128,6.026182,6.080600,6.104134,6.362975,6.481217

In [253]:
co2_by_region_2019 = df.groupby('Region')['2019'].sum().reset_index()
print(co2_by_region_2019)

                       Region        2019
0         East Asia & Pacific  140.142667
1       Europe & Central Asia  286.244383
2   Latin America & Caribbean  100.148730
3  Middle East & North Africa  175.104550
4               North America   30.104023
5                  South Asia   10.304685
6          Sub-Saharan Africa   43.942360

##### **Simple Cleaning**

##### 16. Replace missing values in the year columns with `0`.

In [254]:
df.head()

,Country Name,country_code,Region,Indicator Name,1990,1991,1992,1993,1994,1995,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Aruba,ABW,Latin America & Caribbean,CO2 emissions (metric tons per capita),NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,South Asia,CO2 emissions (metric tons per capita),0.191745,0.167682,0.095958,0.084721,0.075546,0.068468,...,0.243614,0.296506,0.259295,0.185624,0.146236,0.172897,0.149789,0.131695,0.163295,0.159824
2,Angola,AGO,Sub-Saharan Africa,CO2 emissions (metric tons per capita),0.553662,0.544539,0.543557,0.708984,0.836804,0.912141,...,0.976184,0.985522,0.950696,1.036294,1.099779,1.135044,1.031811,0.813301,0.777675,0.792137
3,Albania,ALB,Europe & Central Asia,CO2 emissions (metric tons per capita),1.819542,1.242810,0.683700,0.638307,0.645355,0.605436,...,1.527624,1.669423,1.503240,1.533630,1.668337,1.603775,1.557664,1.788786,1.782739,1.692248
4,Andorra,AND,Europe & Central Asia,CO2 emissions (metric tons per capita),7.521832,7.235379,6.963079,6.724178,6.541579,6.733479,...,6.157198,5.850886,5.944654,5.942800,5.807128,6.026182,6.080600,6.104134,6.362975,6.481217

In [255]:
# year_columns = ['2015', '2016', '2017', '2018', '2019', '2020']
# #If you already know the exact year columns (say, 2015 through 2020), you could also just list them directly instead of using isdigit()
# df[year_columns] = df[year_columns].fillna(0)

# OR

year_columns = [col for col in df.columns if col.isdigit()]
df[year_columns] = df[year_columns].fillna(0)

#[col for col in df.columns if col.isdigit()]
#A list comprehension that grabs only the column names that are purely numeric strings (like '2019', '2020')
#df[year_columns].fillna(0) — replaces any NaN values in those specific columns with 0.
#Assigning it back to df[year_columns] updates the DataFrame in place with the filled values.

In [256]:
df.head()

,Country Name,country_code,Region,Indicator Name,1990,1991,1992,1993,1994,1995,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Aruba,ABW,Latin America & Caribbean,CO2 emissions (metric tons per capita),0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,Afghanistan,AFG,South Asia,CO2 emissions (metric tons per capita),0.191745,0.167682,0.095958,0.084721,0.075546,0.068468,...,0.243614,0.296506,0.259295,0.185624,0.146236,0.172897,0.149789,0.131695,0.163295,0.159824
2,Angola,AGO,Sub-Saharan Africa,CO2 emissions (metric tons per capita),0.553662,0.544539,0.543557,0.708984,0.836804,0.912141,...,0.976184,0.985522,0.950696,1.036294,1.099779,1.135044,1.031811,0.813301,0.777675,0.792137
3,Albania,ALB,Europe & Central Asia,CO2 emissions (metric tons per capita),1.819542,1.242810,0.683700,0.638307,0.645355,0.605436,...,1.527624,1.669423,1.503240,1.533630,1.668337,1.603775,1.557664,1.788786,1.782739,1.692248
4,Andorra,AND,Europe & Central Asia,CO2 emissions (metric tons per capita),7.521832,7.235379,6.963079,6.724178,6.541579,6.733479,...,6.157198,5.850886,5.944654,5.942800,5.807128,6.026182,6.080600,6.104134,6.362975,6.481217

##### 17. Rename the column `Country Name` to `country_name` (no spaces).

In [257]:
df.head()

,Country Name,country_code,Region,Indicator Name,1990,1991,1992,1993,1994,1995,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Aruba,ABW,Latin America & Caribbean,CO2 emissions (metric tons per capita),0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,Afghanistan,AFG,South Asia,CO2 emissions (metric tons per capita),0.191745,0.167682,0.095958,0.084721,0.075546,0.068468,...,0.243614,0.296506,0.259295,0.185624,0.146236,0.172897,0.149789,0.131695,0.163295,0.159824
2,Angola,AGO,Sub-Saharan Africa,CO2 emissions (metric tons per capita),0.553662,0.544539,0.543557,0.708984,0.836804,0.912141,...,0.976184,0.985522,0.950696,1.036294,1.099779,1.135044,1.031811,0.813301,0.777675,0.792137
3,Albania,ALB,Europe & Central Asia,CO2 emissions (metric tons per capita),1.819542,1.242810,0.683700,0.638307,0.645355,0.605436,...,1.527624,1.669423,1.503240,1.533630,1.668337,1.603775,1.557664,1.788786,1.782739,1.692248
4,Andorra,AND,Europe & Central Asia,CO2 emissions (metric tons per capita),7.521832,7.235379,6.963079,6.724178,6.541579,6.733479,...,6.157198,5.850886,5.944654,5.942800,5.807128,6.026182,6.080600,6.104134,6.362975,6.481217

In [258]:
df.rename(columns = {'Country Name': 'country_name'}, inplace = True)

In [260]:
df.head()

,country_name,country_code,Region,Indicator Name,1990,1991,1992,1993,1994,1995,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Aruba,ABW,Latin America & Caribbean,CO2 emissions (metric tons per capita),0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,Afghanistan,AFG,South Asia,CO2 emissions (metric tons per capita),0.191745,0.167682,0.095958,0.084721,0.075546,0.068468,...,0.243614,0.296506,0.259295,0.185624,0.146236,0.172897,0.149789,0.131695,0.163295,0.159824
2,Angola,AGO,Sub-Saharan Africa,CO2 emissions (metric tons per capita),0.553662,0.544539,0.543557,0.708984,0.836804,0.912141,...,0.976184,0.985522,0.950696,1.036294,1.099779,1.135044,1.031811,0.813301,0.777675,0.792137
3,Albania,ALB,Europe & Central Asia,CO2 emissions (metric tons per capita),1.819542,1.242810,0.683700,0.638307,0.645355,0.605436,...,1.527624,1.669423,1.503240,1.533630,1.668337,1.603775,1.557664,1.788786,1.782739,1.692248
4,Andorra,AND,Europe & Central Asia,CO2 emissions (metric tons per capita),7.521832,7.235379,6.963079,6.724178,6.541579,6.733479,...,6.157198,5.850886,5.944654,5.942800,5.807128,6.026182,6.080600,6.104134,6.362975,6.481217

##### 18. Sort the DataFrame by `2019` values, highest to lowest.

In [261]:
df.head()

,country_name,country_code,Region,Indicator Name,1990,1991,1992,1993,1994,1995,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Aruba,ABW,Latin America & Caribbean,CO2 emissions (metric tons per capita),0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,Afghanistan,AFG,South Asia,CO2 emissions (metric tons per capita),0.191745,0.167682,0.095958,0.084721,0.075546,0.068468,...,0.243614,0.296506,0.259295,0.185624,0.146236,0.172897,0.149789,0.131695,0.163295,0.159824
2,Angola,AGO,Sub-Saharan Africa,CO2 emissions (metric tons per capita),0.553662,0.544539,0.543557,0.708984,0.836804,0.912141,...,0.976184,0.985522,0.950696,1.036294,1.099779,1.135044,1.031811,0.813301,0.777675,0.792137
3,Albania,ALB,Europe & Central Asia,CO2 emissions (metric tons per capita),1.819542,1.242810,0.683700,0.638307,0.645355,0.605436,...,1.527624,1.669423,1.503240,1.533630,1.668337,1.603775,1.557664,1.788786,1.782739,1.692248
4,Andorra,AND,Europe & Central Asia,CO2 emissions (metric tons per capita),7.521832,7.235379,6.963079,6.724178,6.541579,6.733479,...,6.157198,5.850886,5.944654,5.942800,5.807128,6.026182,6.080600,6.104134,6.362975,6.481217

In [263]:
df.sort_values(by = '2019', ascending = True)

,country_name,country_code,Region,Indicator Name,1990,1991,1992,1993,1994,1995,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Aruba,ABW,Latin America & Caribbean,CO2 emissions (metric tons per capita),0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
8,American Samoa,ASM,East Asia & Pacific,CO2 emissions (metric tons per capita),0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
24,Bermuda,BMU,North America,CO2 emissions (metric tons per capita),0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
45,Curacao,CUW,Latin America & Caribbean,CO2 emissions (metric tons per capita),0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
46,Cayman Islands,CYM,Latin America & Caribbean,CO2 emissions (metric tons per capita),0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28,Brunei Darussalam,BRN,East Asia & Pacific,CO2 emissions (metric tons per capita),12.600787,12.696839,13.107548,13.951804,14.752014,15.482377,...,18.449235,18.618852,18.295877,17.828265,17.277648,15.424883,16.603500,17.173913,17.577396,16.132159
5,United Arab Emirates,ARE,Middle East & North Africa,CO2 emissions (metric tons per capita),30.195189,31.778496,29.080926,29.275678,30.849333,31.125018,...,19.039770,18.509457,19.207801,20.055648,20.051698,21.077642,21.480669,20.769022,18.390678,19.329563
19,Bahrain,BHR,Middle East & North Africa,CO2 emissions (metric tons per capita),21.656413,20.303593,23.457125,24.374688,24.327226,24.019954,...,20.928965,20.357501,20.900933,21.938680,22.663433,22.291018,21.251331,20.427328,19.631206,20.266103
105,Kuwait,KWT,Middle East & North Africa,CO2 emissions (metric tons per capita),13.902212,3.849757,0.000000,0.000000,0.000000,22.572914,...,26.979656,26.290588,25.474401,24.773266,23.183802,23.208957,23.137022,22.368768,22.089210,22.022416
162,Qatar,QAT,Middle East & North Africa,CO2 emissions (metric tons per capita),26.329327,30.737411,29.632441,33.122025,36.466263,37.102174,...,32.634302,33.494413,34.188222,32.598940,33.205895,33.043510,32.745888,32.127990,31.067533,32.474469

##### 19. Filter out rows where `2019` value is missing (`NaN`).

In [ ]:
# **Simple Visualization**
# 20. Plot a bar chart of the top 10 countries by 2019 CO2 emissions using matplotlib.